{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  namespace: {{ include "carbide-rest-common.namespace" . }}
  labels:
    {{- include "carbide-rest-common.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.dbCreds.username | quote }}
  password: {{ .Values.secrets.dbCreds.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secret
  namespace: {{ include "carbide-rest-common.namespace" . }}
  labels:
    {{- include "carbide-rest-common.labels" . | nindent 4 }}
type: Opaque
stringData:
  keycloak-client-secret: {{ .Values.secrets.keycloakClientSecret.value | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: temporal-encryption-key
  namespace: {{ include "carbide-rest-common.namespace" . }}
  labels:
    {{- include "carbide-rest-common.labels" . | nindent 4 }}
type: Opaque
stringData:
  temporal-encryption-key: {{ .Values.secrets.temporalEncryptionKey.value | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
  namespace: {{ include "carbide-rest-common.namespace" . }}
  labels:
    {{- include "carbide-rest-common.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.imagePullSecret.dockerconfigjson | quote }}
{{- end }}
