/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the FaultIngestionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FaultIngestionRequest{}

// FaultIngestionRequest Webhook payload for fault ingestion from external monitoring systems.
type FaultIngestionRequest struct {
	Source         string                 `json:"source"`
	Severity       string                 `json:"severity"`
	Component      string                 `json:"component"`
	Classification *string                `json:"classification,omitempty"`
	Message        string                 `json:"message"`
	MachineId      *string                `json:"machine_id,omitempty"`
	DetectedAt     *time.Time             `json:"detected_at,omitempty"`
	Metadata       map[string]interface{} `json:"metadata,omitempty"`
}

type _FaultIngestionRequest FaultIngestionRequest

// NewFaultIngestionRequest instantiates a new FaultIngestionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFaultIngestionRequest(source string, severity string, component string, message string) *FaultIngestionRequest {
	this := FaultIngestionRequest{}
	this.Source = source
	this.Severity = severity
	this.Component = component
	this.Message = message
	return &this
}

// NewFaultIngestionRequestWithDefaults instantiates a new FaultIngestionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFaultIngestionRequestWithDefaults() *FaultIngestionRequest {
	this := FaultIngestionRequest{}
	return &this
}

// GetSource returns the Source field value
func (o *FaultIngestionRequest) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *FaultIngestionRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *FaultIngestionRequest) SetSource(v string) {
	o.Source = v
}

// GetSeverity returns the Severity field value
func (o *FaultIngestionRequest) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *FaultIngestionRequest) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *FaultIngestionRequest) SetSeverity(v string) {
	o.Severity = v
}

// GetComponent returns the Component field value
func (o *FaultIngestionRequest) GetComponent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Component
}

// GetComponentOk returns a tuple with the Component field value
// and a boolean to check if the value has been set.
func (o *FaultIngestionRequest) GetComponentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Component, true
}

// SetComponent sets field value
func (o *FaultIngestionRequest) SetComponent(v string) {
	o.Component = v
}

// GetClassification returns the Classification field value if set, zero value otherwise.
func (o *FaultIngestionRequest) GetClassification() string {
	if o == nil || IsNil(o.Classification) {
		var ret string
		return ret
	}
	return *o.Classification
}

// GetClassificationOk returns a tuple with the Classification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultIngestionRequest) GetClassificationOk() (*string, bool) {
	if o == nil || IsNil(o.Classification) {
		return nil, false
	}
	return o.Classification, true
}

// HasClassification returns a boolean if a field has been set.
func (o *FaultIngestionRequest) HasClassification() bool {
	if o != nil && !IsNil(o.Classification) {
		return true
	}

	return false
}

// SetClassification gets a reference to the given string and assigns it to the Classification field.
func (o *FaultIngestionRequest) SetClassification(v string) {
	o.Classification = &v
}

// GetMessage returns the Message field value
func (o *FaultIngestionRequest) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *FaultIngestionRequest) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *FaultIngestionRequest) SetMessage(v string) {
	o.Message = v
}

// GetMachineId returns the MachineId field value if set, zero value otherwise.
func (o *FaultIngestionRequest) GetMachineId() string {
	if o == nil || IsNil(o.MachineId) {
		var ret string
		return ret
	}
	return *o.MachineId
}

// GetMachineIdOk returns a tuple with the MachineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultIngestionRequest) GetMachineIdOk() (*string, bool) {
	if o == nil || IsNil(o.MachineId) {
		return nil, false
	}
	return o.MachineId, true
}

// HasMachineId returns a boolean if a field has been set.
func (o *FaultIngestionRequest) HasMachineId() bool {
	if o != nil && !IsNil(o.MachineId) {
		return true
	}

	return false
}

// SetMachineId gets a reference to the given string and assigns it to the MachineId field.
func (o *FaultIngestionRequest) SetMachineId(v string) {
	o.MachineId = &v
}

// GetDetectedAt returns the DetectedAt field value if set, zero value otherwise.
func (o *FaultIngestionRequest) GetDetectedAt() time.Time {
	if o == nil || IsNil(o.DetectedAt) {
		var ret time.Time
		return ret
	}
	return *o.DetectedAt
}

// GetDetectedAtOk returns a tuple with the DetectedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultIngestionRequest) GetDetectedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DetectedAt) {
		return nil, false
	}
	return o.DetectedAt, true
}

// HasDetectedAt returns a boolean if a field has been set.
func (o *FaultIngestionRequest) HasDetectedAt() bool {
	if o != nil && !IsNil(o.DetectedAt) {
		return true
	}

	return false
}

// SetDetectedAt gets a reference to the given time.Time and assigns it to the DetectedAt field.
func (o *FaultIngestionRequest) SetDetectedAt(v time.Time) {
	o.DetectedAt = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *FaultIngestionRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultIngestionRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *FaultIngestionRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *FaultIngestionRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o FaultIngestionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FaultIngestionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["severity"] = o.Severity
	toSerialize["component"] = o.Component
	if !IsNil(o.Classification) {
		toSerialize["classification"] = o.Classification
	}
	toSerialize["message"] = o.Message
	if !IsNil(o.MachineId) {
		toSerialize["machine_id"] = o.MachineId
	}
	if !IsNil(o.DetectedAt) {
		toSerialize["detected_at"] = o.DetectedAt
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *FaultIngestionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"severity",
		"component",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFaultIngestionRequest := _FaultIngestionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFaultIngestionRequest)

	if err != nil {
		return err
	}

	*o = FaultIngestionRequest(varFaultIngestionRequest)

	return err
}

type NullableFaultIngestionRequest struct {
	value *FaultIngestionRequest
	isSet bool
}

func (v NullableFaultIngestionRequest) Get() *FaultIngestionRequest {
	return v.value
}

func (v *NullableFaultIngestionRequest) Set(val *FaultIngestionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFaultIngestionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFaultIngestionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFaultIngestionRequest(val *FaultIngestionRequest) *NullableFaultIngestionRequest {
	return &NullableFaultIngestionRequest{value: val, isSet: true}
}

func (v NullableFaultIngestionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFaultIngestionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
