/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the ValidateBlueprint200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateBlueprint200Response{}

// ValidateBlueprint200Response struct for ValidateBlueprint200Response
type ValidateBlueprint200Response struct {
	Valid  *bool    `json:"valid,omitempty"`
	Errors []string `json:"errors,omitempty"`
}

// NewValidateBlueprint200Response instantiates a new ValidateBlueprint200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateBlueprint200Response() *ValidateBlueprint200Response {
	this := ValidateBlueprint200Response{}
	return &this
}

// NewValidateBlueprint200ResponseWithDefaults instantiates a new ValidateBlueprint200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateBlueprint200ResponseWithDefaults() *ValidateBlueprint200Response {
	this := ValidateBlueprint200Response{}
	return &this
}

// GetValid returns the Valid field value if set, zero value otherwise.
func (o *ValidateBlueprint200Response) GetValid() bool {
	if o == nil || IsNil(o.Valid) {
		var ret bool
		return ret
	}
	return *o.Valid
}

// GetValidOk returns a tuple with the Valid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateBlueprint200Response) GetValidOk() (*bool, bool) {
	if o == nil || IsNil(o.Valid) {
		return nil, false
	}
	return o.Valid, true
}

// HasValid returns a boolean if a field has been set.
func (o *ValidateBlueprint200Response) HasValid() bool {
	if o != nil && !IsNil(o.Valid) {
		return true
	}

	return false
}

// SetValid gets a reference to the given bool and assigns it to the Valid field.
func (o *ValidateBlueprint200Response) SetValid(v bool) {
	o.Valid = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ValidateBlueprint200Response) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateBlueprint200Response) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ValidateBlueprint200Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *ValidateBlueprint200Response) SetErrors(v []string) {
	o.Errors = v
}

func (o ValidateBlueprint200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateBlueprint200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Valid) {
		toSerialize["valid"] = o.Valid
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableValidateBlueprint200Response struct {
	value *ValidateBlueprint200Response
	isSet bool
}

func (v NullableValidateBlueprint200Response) Get() *ValidateBlueprint200Response {
	return v.value
}

func (v *NullableValidateBlueprint200Response) Set(val *ValidateBlueprint200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateBlueprint200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateBlueprint200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateBlueprint200Response(val *ValidateBlueprint200Response) *NullableValidateBlueprint200Response {
	return &NullableValidateBlueprint200Response{value: val, isSet: true}
}

func (v NullableValidateBlueprint200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateBlueprint200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
