/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the DPUDeploymentReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DPUDeploymentReference{}

// DPUDeploymentReference Identifies a DPU deployment by name and namespace.
type DPUDeploymentReference struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// NewDPUDeploymentReference instantiates a new DPUDeploymentReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDPUDeploymentReference() *DPUDeploymentReference {
	this := DPUDeploymentReference{}
	return &this
}

// NewDPUDeploymentReferenceWithDefaults instantiates a new DPUDeploymentReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDPUDeploymentReferenceWithDefaults() *DPUDeploymentReference {
	this := DPUDeploymentReference{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DPUDeploymentReference) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DPUDeploymentReference) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DPUDeploymentReference) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DPUDeploymentReference) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *DPUDeploymentReference) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DPUDeploymentReference) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *DPUDeploymentReference) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *DPUDeploymentReference) SetNamespace(v string) {
	o.Namespace = &v
}

func (o DPUDeploymentReference) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DPUDeploymentReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	return toSerialize, nil
}

type NullableDPUDeploymentReference struct {
	value *DPUDeploymentReference
	isSet bool
}

func (v NullableDPUDeploymentReference) Get() *DPUDeploymentReference {
	return v.value
}

func (v *NullableDPUDeploymentReference) Set(val *DPUDeploymentReference) {
	v.value = val
	v.isSet = true
}

func (v NullableDPUDeploymentReference) IsSet() bool {
	return v.isSet
}

func (v *NullableDPUDeploymentReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDPUDeploymentReference(val *DPUDeploymentReference) *NullableDPUDeploymentReference {
	return &NullableDPUDeploymentReference{value: val, isSet: true}
}

func (v NullableDPUDeploymentReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDPUDeploymentReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
