/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the FulfillmentServiceListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FulfillmentServiceListResponse{}

// FulfillmentServiceListResponse struct for FulfillmentServiceListResponse
type FulfillmentServiceListResponse struct {
	Items  []FulfillmentService `json:"items,omitempty"`
	Total  *int32               `json:"total,omitempty"`
	Offset *int32               `json:"offset,omitempty"`
	Limit  *int32               `json:"limit,omitempty"`
}

// NewFulfillmentServiceListResponse instantiates a new FulfillmentServiceListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFulfillmentServiceListResponse() *FulfillmentServiceListResponse {
	this := FulfillmentServiceListResponse{}
	return &this
}

// NewFulfillmentServiceListResponseWithDefaults instantiates a new FulfillmentServiceListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFulfillmentServiceListResponseWithDefaults() *FulfillmentServiceListResponse {
	this := FulfillmentServiceListResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *FulfillmentServiceListResponse) GetItems() []FulfillmentService {
	if o == nil || IsNil(o.Items) {
		var ret []FulfillmentService
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentServiceListResponse) GetItemsOk() ([]FulfillmentService, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *FulfillmentServiceListResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []FulfillmentService and assigns it to the Items field.
func (o *FulfillmentServiceListResponse) SetItems(v []FulfillmentService) {
	o.Items = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *FulfillmentServiceListResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentServiceListResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *FulfillmentServiceListResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *FulfillmentServiceListResponse) SetTotal(v int32) {
	o.Total = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *FulfillmentServiceListResponse) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentServiceListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *FulfillmentServiceListResponse) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *FulfillmentServiceListResponse) SetOffset(v int32) {
	o.Offset = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *FulfillmentServiceListResponse) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentServiceListResponse) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *FulfillmentServiceListResponse) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *FulfillmentServiceListResponse) SetLimit(v int32) {
	o.Limit = &v
}

func (o FulfillmentServiceListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FulfillmentServiceListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	return toSerialize, nil
}

type NullableFulfillmentServiceListResponse struct {
	value *FulfillmentServiceListResponse
	isSet bool
}

func (v NullableFulfillmentServiceListResponse) Get() *FulfillmentServiceListResponse {
	return v.value
}

func (v *NullableFulfillmentServiceListResponse) Set(val *FulfillmentServiceListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFulfillmentServiceListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFulfillmentServiceListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFulfillmentServiceListResponse(val *FulfillmentServiceListResponse) *NullableFulfillmentServiceListResponse {
	return &NullableFulfillmentServiceListResponse{value: val, isSet: true}
}

func (v NullableFulfillmentServiceListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFulfillmentServiceListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
