/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the FeatureStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureStatus{}

// FeatureStatus Runtime status of a single feature.
type FeatureStatus struct {
	Status *string `json:"status,omitempty"`
	// Provider name (set when available)
	Provider *string `json:"provider,omitempty"`
	// Provider version (set when available)
	Version *string `json:"version,omitempty"`
}

// NewFeatureStatus instantiates a new FeatureStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureStatus() *FeatureStatus {
	this := FeatureStatus{}
	return &this
}

// NewFeatureStatusWithDefaults instantiates a new FeatureStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureStatusWithDefaults() *FeatureStatus {
	this := FeatureStatus{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *FeatureStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *FeatureStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *FeatureStatus) SetStatus(v string) {
	o.Status = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *FeatureStatus) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureStatus) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *FeatureStatus) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *FeatureStatus) SetProvider(v string) {
	o.Provider = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *FeatureStatus) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureStatus) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *FeatureStatus) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *FeatureStatus) SetVersion(v string) {
	o.Version = &v
}

func (o FeatureStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableFeatureStatus struct {
	value *FeatureStatus
	isSet bool
}

func (v NullableFeatureStatus) Get() *FeatureStatus {
	return v.value
}

func (v *NullableFeatureStatus) Set(val *FeatureStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureStatus(val *FeatureStatus) *NullableFeatureStatus {
	return &NullableFeatureStatus{value: val, isSet: true}
}

func (v NullableFeatureStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
