/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the UsageSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageSummary{}

// UsageSummary Aggregated usage metrics for a tenant or service over a period.
type UsageSummary struct {
	TenantId *string `json:"tenant_id,omitempty"`
	// Billing period (e.g., \"current-month\", \"last-30d\")
	Period *string `json:"period,omitempty"`
	// Metric name to aggregated value (e.g., \"gpu-hours\": 1234.5)
	Metrics map[string]float32 `json:"metrics,omitempty"`
}

// NewUsageSummary instantiates a new UsageSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageSummary() *UsageSummary {
	this := UsageSummary{}
	return &this
}

// NewUsageSummaryWithDefaults instantiates a new UsageSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageSummaryWithDefaults() *UsageSummary {
	this := UsageSummary{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *UsageSummary) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageSummary) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *UsageSummary) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *UsageSummary) SetTenantId(v string) {
	o.TenantId = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *UsageSummary) GetPeriod() string {
	if o == nil || IsNil(o.Period) {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageSummary) GetPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *UsageSummary) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *UsageSummary) SetPeriod(v string) {
	o.Period = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *UsageSummary) GetMetrics() map[string]float32 {
	if o == nil || IsNil(o.Metrics) {
		var ret map[string]float32
		return ret
	}
	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageSummary) GetMetricsOk() (map[string]float32, bool) {
	if o == nil || IsNil(o.Metrics) {
		return map[string]float32{}, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *UsageSummary) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given map[string]float32 and assigns it to the Metrics field.
func (o *UsageSummary) SetMetrics(v map[string]float32) {
	o.Metrics = v
}

func (o UsageSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	return toSerialize, nil
}

type NullableUsageSummary struct {
	value *UsageSummary
	isSet bool
}

func (v NullableUsageSummary) Get() *UsageSummary {
	return v.value
}

func (v *NullableUsageSummary) Set(val *UsageSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageSummary(val *UsageSummary) *NullableUsageSummary {
	return &NullableUsageSummary{value: val, isSet: true}
}

func (v NullableUsageSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
