/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the ProvisioningRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProvisioningRecord{}

// ProvisioningRecord Tracks the state of a DPF HCP provisioning request for a site.
type ProvisioningRecord struct {
	SiteId      *string           `json:"siteId,omitempty"`
	Config      *DPFHCPRequest    `json:"config,omitempty"`
	Status      *string           `json:"status,omitempty"`
	Phase       *string           `json:"phase,omitempty"`
	Conditions  []StatusCondition `json:"conditions,omitempty"`
	WorkflowId  *string           `json:"workflowId,omitempty"`
	CrName      *string           `json:"crName,omitempty"`
	CrNamespace *string           `json:"crNamespace,omitempty"`
	Created     *time.Time        `json:"created,omitempty"`
	Updated     *time.Time        `json:"updated,omitempty"`
}

// NewProvisioningRecord instantiates a new ProvisioningRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvisioningRecord() *ProvisioningRecord {
	this := ProvisioningRecord{}
	return &this
}

// NewProvisioningRecordWithDefaults instantiates a new ProvisioningRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvisioningRecordWithDefaults() *ProvisioningRecord {
	this := ProvisioningRecord{}
	return &this
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *ProvisioningRecord) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningRecord) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *ProvisioningRecord) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *ProvisioningRecord) SetSiteId(v string) {
	o.SiteId = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *ProvisioningRecord) GetConfig() DPFHCPRequest {
	if o == nil || IsNil(o.Config) {
		var ret DPFHCPRequest
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningRecord) GetConfigOk() (*DPFHCPRequest, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *ProvisioningRecord) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given DPFHCPRequest and assigns it to the Config field.
func (o *ProvisioningRecord) SetConfig(v DPFHCPRequest) {
	o.Config = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ProvisioningRecord) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningRecord) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ProvisioningRecord) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ProvisioningRecord) SetStatus(v string) {
	o.Status = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *ProvisioningRecord) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningRecord) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *ProvisioningRecord) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *ProvisioningRecord) SetPhase(v string) {
	o.Phase = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *ProvisioningRecord) GetConditions() []StatusCondition {
	if o == nil || IsNil(o.Conditions) {
		var ret []StatusCondition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningRecord) GetConditionsOk() ([]StatusCondition, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *ProvisioningRecord) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []StatusCondition and assigns it to the Conditions field.
func (o *ProvisioningRecord) SetConditions(v []StatusCondition) {
	o.Conditions = v
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *ProvisioningRecord) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningRecord) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *ProvisioningRecord) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *ProvisioningRecord) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

// GetCrName returns the CrName field value if set, zero value otherwise.
func (o *ProvisioningRecord) GetCrName() string {
	if o == nil || IsNil(o.CrName) {
		var ret string
		return ret
	}
	return *o.CrName
}

// GetCrNameOk returns a tuple with the CrName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningRecord) GetCrNameOk() (*string, bool) {
	if o == nil || IsNil(o.CrName) {
		return nil, false
	}
	return o.CrName, true
}

// HasCrName returns a boolean if a field has been set.
func (o *ProvisioningRecord) HasCrName() bool {
	if o != nil && !IsNil(o.CrName) {
		return true
	}

	return false
}

// SetCrName gets a reference to the given string and assigns it to the CrName field.
func (o *ProvisioningRecord) SetCrName(v string) {
	o.CrName = &v
}

// GetCrNamespace returns the CrNamespace field value if set, zero value otherwise.
func (o *ProvisioningRecord) GetCrNamespace() string {
	if o == nil || IsNil(o.CrNamespace) {
		var ret string
		return ret
	}
	return *o.CrNamespace
}

// GetCrNamespaceOk returns a tuple with the CrNamespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningRecord) GetCrNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.CrNamespace) {
		return nil, false
	}
	return o.CrNamespace, true
}

// HasCrNamespace returns a boolean if a field has been set.
func (o *ProvisioningRecord) HasCrNamespace() bool {
	if o != nil && !IsNil(o.CrNamespace) {
		return true
	}

	return false
}

// SetCrNamespace gets a reference to the given string and assigns it to the CrNamespace field.
func (o *ProvisioningRecord) SetCrNamespace(v string) {
	o.CrNamespace = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ProvisioningRecord) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningRecord) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ProvisioningRecord) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ProvisioningRecord) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ProvisioningRecord) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningRecord) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ProvisioningRecord) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *ProvisioningRecord) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o ProvisioningRecord) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProvisioningRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflowId"] = o.WorkflowId
	}
	if !IsNil(o.CrName) {
		toSerialize["crName"] = o.CrName
	}
	if !IsNil(o.CrNamespace) {
		toSerialize["crNamespace"] = o.CrNamespace
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableProvisioningRecord struct {
	value *ProvisioningRecord
	isSet bool
}

func (v NullableProvisioningRecord) Get() *ProvisioningRecord {
	return v.value
}

func (v *NullableProvisioningRecord) Set(val *ProvisioningRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableProvisioningRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableProvisioningRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvisioningRecord(val *ProvisioningRecord) *NullableProvisioningRecord {
	return &NullableProvisioningRecord{value: val, isSet: true}
}

func (v NullableProvisioningRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvisioningRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
