/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the CapabilitiesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CapabilitiesResponse{}

// CapabilitiesResponse Feature capability status for the deployment.
type CapabilitiesResponse struct {
	Features map[string]FeatureStatus `json:"features,omitempty"`
}

// NewCapabilitiesResponse instantiates a new CapabilitiesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapabilitiesResponse() *CapabilitiesResponse {
	this := CapabilitiesResponse{}
	return &this
}

// NewCapabilitiesResponseWithDefaults instantiates a new CapabilitiesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapabilitiesResponseWithDefaults() *CapabilitiesResponse {
	this := CapabilitiesResponse{}
	return &this
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *CapabilitiesResponse) GetFeatures() map[string]FeatureStatus {
	if o == nil || IsNil(o.Features) {
		var ret map[string]FeatureStatus
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CapabilitiesResponse) GetFeaturesOk() (map[string]FeatureStatus, bool) {
	if o == nil || IsNil(o.Features) {
		return map[string]FeatureStatus{}, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *CapabilitiesResponse) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given map[string]FeatureStatus and assigns it to the Features field.
func (o *CapabilitiesResponse) SetFeatures(v map[string]FeatureStatus) {
	o.Features = v
}

func (o CapabilitiesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CapabilitiesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	return toSerialize, nil
}

type NullableCapabilitiesResponse struct {
	value *CapabilitiesResponse
	isSet bool
}

func (v NullableCapabilitiesResponse) Get() *CapabilitiesResponse {
	return v.value
}

func (v *NullableCapabilitiesResponse) Set(val *CapabilitiesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCapabilitiesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCapabilitiesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapabilitiesResponse(val *CapabilitiesResponse) *NullableCapabilitiesResponse {
	return &NullableCapabilitiesResponse{value: val, isSet: true}
}

func (v NullableCapabilitiesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapabilitiesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
