/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the UpdateFaultEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateFaultEventRequest{}

// UpdateFaultEventRequest Request body for updating a fault event (acknowledge, suppress, resolve).
type UpdateFaultEventRequest struct {
	State           *string                `json:"state,omitempty"`
	SuppressedUntil *time.Time             `json:"suppressed_until,omitempty"`
	Metadata        map[string]interface{} `json:"metadata,omitempty"`
}

// NewUpdateFaultEventRequest instantiates a new UpdateFaultEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateFaultEventRequest() *UpdateFaultEventRequest {
	this := UpdateFaultEventRequest{}
	return &this
}

// NewUpdateFaultEventRequestWithDefaults instantiates a new UpdateFaultEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateFaultEventRequestWithDefaults() *UpdateFaultEventRequest {
	this := UpdateFaultEventRequest{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *UpdateFaultEventRequest) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFaultEventRequest) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *UpdateFaultEventRequest) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *UpdateFaultEventRequest) SetState(v string) {
	o.State = &v
}

// GetSuppressedUntil returns the SuppressedUntil field value if set, zero value otherwise.
func (o *UpdateFaultEventRequest) GetSuppressedUntil() time.Time {
	if o == nil || IsNil(o.SuppressedUntil) {
		var ret time.Time
		return ret
	}
	return *o.SuppressedUntil
}

// GetSuppressedUntilOk returns a tuple with the SuppressedUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFaultEventRequest) GetSuppressedUntilOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SuppressedUntil) {
		return nil, false
	}
	return o.SuppressedUntil, true
}

// HasSuppressedUntil returns a boolean if a field has been set.
func (o *UpdateFaultEventRequest) HasSuppressedUntil() bool {
	if o != nil && !IsNil(o.SuppressedUntil) {
		return true
	}

	return false
}

// SetSuppressedUntil gets a reference to the given time.Time and assigns it to the SuppressedUntil field.
func (o *UpdateFaultEventRequest) SetSuppressedUntil(v time.Time) {
	o.SuppressedUntil = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *UpdateFaultEventRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFaultEventRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *UpdateFaultEventRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *UpdateFaultEventRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o UpdateFaultEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateFaultEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.SuppressedUntil) {
		toSerialize["suppressed_until"] = o.SuppressedUntil
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableUpdateFaultEventRequest struct {
	value *UpdateFaultEventRequest
	isSet bool
}

func (v NullableUpdateFaultEventRequest) Get() *UpdateFaultEventRequest {
	return v.value
}

func (v *NullableUpdateFaultEventRequest) Set(val *UpdateFaultEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFaultEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFaultEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFaultEventRequest(val *UpdateFaultEventRequest) *NullableUpdateFaultEventRequest {
	return &NullableUpdateFaultEventRequest{value: val, isSet: true}
}

func (v NullableUpdateFaultEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFaultEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
