/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the UpdateServiceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateServiceRequest{}

// UpdateServiceRequest Request body for updating a provisioned service.
type UpdateServiceRequest struct {
	Name      *string           `json:"name,omitempty"`
	Resources map[string]string `json:"resources,omitempty"`
}

// NewUpdateServiceRequest instantiates a new UpdateServiceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateServiceRequest() *UpdateServiceRequest {
	this := UpdateServiceRequest{}
	return &this
}

// NewUpdateServiceRequestWithDefaults instantiates a new UpdateServiceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateServiceRequestWithDefaults() *UpdateServiceRequest {
	this := UpdateServiceRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateServiceRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateServiceRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateServiceRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateServiceRequest) SetName(v string) {
	o.Name = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *UpdateServiceRequest) GetResources() map[string]string {
	if o == nil || IsNil(o.Resources) {
		var ret map[string]string
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateServiceRequest) GetResourcesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Resources) {
		return map[string]string{}, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *UpdateServiceRequest) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given map[string]string and assigns it to the Resources field.
func (o *UpdateServiceRequest) SetResources(v map[string]string) {
	o.Resources = v
}

func (o UpdateServiceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateServiceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	return toSerialize, nil
}

type NullableUpdateServiceRequest struct {
	value *UpdateServiceRequest
	isSet bool
}

func (v NullableUpdateServiceRequest) Get() *UpdateServiceRequest {
	return v.value
}

func (v *NullableUpdateServiceRequest) Set(val *UpdateServiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateServiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateServiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateServiceRequest(val *UpdateServiceRequest) *NullableUpdateServiceRequest {
	return &NullableUpdateServiceRequest{value: val, isSet: true}
}

func (v NullableUpdateServiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateServiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
