/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DPUClusterReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DPUClusterReference{}

// DPUClusterReference Identifies a DPU cluster by name and namespace.
type DPUClusterReference struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type _DPUClusterReference DPUClusterReference

// NewDPUClusterReference instantiates a new DPUClusterReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDPUClusterReference(name string, namespace string) *DPUClusterReference {
	this := DPUClusterReference{}
	this.Name = name
	this.Namespace = namespace
	return &this
}

// NewDPUClusterReferenceWithDefaults instantiates a new DPUClusterReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDPUClusterReferenceWithDefaults() *DPUClusterReference {
	this := DPUClusterReference{}
	return &this
}

// GetName returns the Name field value
func (o *DPUClusterReference) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DPUClusterReference) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DPUClusterReference) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value
func (o *DPUClusterReference) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *DPUClusterReference) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *DPUClusterReference) SetNamespace(v string) {
	o.Namespace = v
}

func (o DPUClusterReference) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DPUClusterReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["namespace"] = o.Namespace
	return toSerialize, nil
}

func (o *DPUClusterReference) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"namespace",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDPUClusterReference := _DPUClusterReference{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDPUClusterReference)

	if err != nil {
		return err
	}

	*o = DPUClusterReference(varDPUClusterReference)

	return err
}

type NullableDPUClusterReference struct {
	value *DPUClusterReference
	isSet bool
}

func (v NullableDPUClusterReference) Get() *DPUClusterReference {
	return v.value
}

func (v *NullableDPUClusterReference) Set(val *DPUClusterReference) {
	v.value = val
	v.isSet = true
}

func (v NullableDPUClusterReference) IsSet() bool {
	return v.isSet
}

func (v *NullableDPUClusterReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDPUClusterReference(val *DPUClusterReference) *NullableDPUClusterReference {
	return &NullableDPUClusterReference{value: val, isSet: true}
}

func (v NullableDPUClusterReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDPUClusterReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
