/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Blueprint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Blueprint{}

// Blueprint struct for Blueprint
type Blueprint struct {
	Id          string                        `json:"id"`
	Name        string                        `json:"name"`
	Version     string                        `json:"version"`
	Description *string                       `json:"description,omitempty"`
	Parameters  map[string]BlueprintParameter `json:"parameters,omitempty"`
	Resources   map[string]BlueprintResource  `json:"resources,omitempty"`
	Labels      map[string]string             `json:"labels,omitempty"`
	Pricing     *PricingSpec                  `json:"pricing,omitempty"`
	TenantId    *string                       `json:"tenant_id,omitempty"`
	Visibility  string                        `json:"visibility"`
	BasedOn     *string                       `json:"based_on,omitempty"`
	IsActive    bool                          `json:"is_active"`
	Created     *time.Time                    `json:"created,omitempty"`
	Updated     *time.Time                    `json:"updated,omitempty"`
}

type _Blueprint Blueprint

// NewBlueprint instantiates a new Blueprint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprint(id string, name string, version string, visibility string, isActive bool) *Blueprint {
	this := Blueprint{}
	this.Id = id
	this.Name = name
	this.Version = version
	this.Visibility = visibility
	this.IsActive = isActive
	return &this
}

// NewBlueprintWithDefaults instantiates a new Blueprint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintWithDefaults() *Blueprint {
	this := Blueprint{}
	return &this
}

// GetId returns the Id field value
func (o *Blueprint) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Blueprint) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Blueprint) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Blueprint) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Blueprint) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Blueprint) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *Blueprint) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *Blueprint) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *Blueprint) SetVersion(v string) {
	o.Version = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Blueprint) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blueprint) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Blueprint) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Blueprint) SetDescription(v string) {
	o.Description = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *Blueprint) GetParameters() map[string]BlueprintParameter {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]BlueprintParameter
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blueprint) GetParametersOk() (map[string]BlueprintParameter, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]BlueprintParameter{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *Blueprint) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]BlueprintParameter and assigns it to the Parameters field.
func (o *Blueprint) SetParameters(v map[string]BlueprintParameter) {
	o.Parameters = v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *Blueprint) GetResources() map[string]BlueprintResource {
	if o == nil || IsNil(o.Resources) {
		var ret map[string]BlueprintResource
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blueprint) GetResourcesOk() (map[string]BlueprintResource, bool) {
	if o == nil || IsNil(o.Resources) {
		return map[string]BlueprintResource{}, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *Blueprint) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given map[string]BlueprintResource and assigns it to the Resources field.
func (o *Blueprint) SetResources(v map[string]BlueprintResource) {
	o.Resources = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *Blueprint) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blueprint) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *Blueprint) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *Blueprint) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetPricing returns the Pricing field value if set, zero value otherwise.
func (o *Blueprint) GetPricing() PricingSpec {
	if o == nil || IsNil(o.Pricing) {
		var ret PricingSpec
		return ret
	}
	return *o.Pricing
}

// GetPricingOk returns a tuple with the Pricing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blueprint) GetPricingOk() (*PricingSpec, bool) {
	if o == nil || IsNil(o.Pricing) {
		return nil, false
	}
	return o.Pricing, true
}

// HasPricing returns a boolean if a field has been set.
func (o *Blueprint) HasPricing() bool {
	if o != nil && !IsNil(o.Pricing) {
		return true
	}

	return false
}

// SetPricing gets a reference to the given PricingSpec and assigns it to the Pricing field.
func (o *Blueprint) SetPricing(v PricingSpec) {
	o.Pricing = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *Blueprint) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blueprint) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *Blueprint) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *Blueprint) SetTenantId(v string) {
	o.TenantId = &v
}

// GetVisibility returns the Visibility field value
func (o *Blueprint) GetVisibility() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value
// and a boolean to check if the value has been set.
func (o *Blueprint) GetVisibilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visibility, true
}

// SetVisibility sets field value
func (o *Blueprint) SetVisibility(v string) {
	o.Visibility = v
}

// GetBasedOn returns the BasedOn field value if set, zero value otherwise.
func (o *Blueprint) GetBasedOn() string {
	if o == nil || IsNil(o.BasedOn) {
		var ret string
		return ret
	}
	return *o.BasedOn
}

// GetBasedOnOk returns a tuple with the BasedOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blueprint) GetBasedOnOk() (*string, bool) {
	if o == nil || IsNil(o.BasedOn) {
		return nil, false
	}
	return o.BasedOn, true
}

// HasBasedOn returns a boolean if a field has been set.
func (o *Blueprint) HasBasedOn() bool {
	if o != nil && !IsNil(o.BasedOn) {
		return true
	}

	return false
}

// SetBasedOn gets a reference to the given string and assigns it to the BasedOn field.
func (o *Blueprint) SetBasedOn(v string) {
	o.BasedOn = &v
}

// GetIsActive returns the IsActive field value
func (o *Blueprint) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *Blueprint) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *Blueprint) SetIsActive(v bool) {
	o.IsActive = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *Blueprint) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blueprint) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *Blueprint) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *Blueprint) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *Blueprint) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Blueprint) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *Blueprint) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *Blueprint) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o Blueprint) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Blueprint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Pricing) {
		toSerialize["pricing"] = o.Pricing
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	toSerialize["visibility"] = o.Visibility
	if !IsNil(o.BasedOn) {
		toSerialize["based_on"] = o.BasedOn
	}
	toSerialize["is_active"] = o.IsActive
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

func (o *Blueprint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"version",
		"visibility",
		"is_active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlueprint := _Blueprint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBlueprint)

	if err != nil {
		return err
	}

	*o = Blueprint(varBlueprint)

	return err
}

type NullableBlueprint struct {
	value *Blueprint
	isSet bool
}

func (v NullableBlueprint) Get() *Blueprint {
	return v.value
}

func (v *NullableBlueprint) Set(val *Blueprint) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprint) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprint(val *Blueprint) *NullableBlueprint {
	return &NullableBlueprint{value: val, isSet: true}
}

func (v NullableBlueprint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
