/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the ServiceEventResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceEventResponse{}

// ServiceEventResponse Tenant-safe view of a service disruption. No infrastructure details (machine IDs, rack locations, classifications) are exposed.
type ServiceEventResponse struct {
	Id                    *string    `json:"id,omitempty"`
	Summary               *string    `json:"summary,omitempty"`
	Impact                *string    `json:"impact,omitempty"`
	State                 *string    `json:"state,omitempty"`
	StartedAt             *time.Time `json:"started_at,omitempty"`
	EstimatedResolutionAt *time.Time `json:"estimated_resolution_at,omitempty"`
	ResolvedAt            *time.Time `json:"resolved_at,omitempty"`
	DowntimeExcluded      *bool      `json:"downtime_excluded,omitempty"`
}

// NewServiceEventResponse instantiates a new ServiceEventResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceEventResponse() *ServiceEventResponse {
	this := ServiceEventResponse{}
	return &this
}

// NewServiceEventResponseWithDefaults instantiates a new ServiceEventResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceEventResponseWithDefaults() *ServiceEventResponse {
	this := ServiceEventResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServiceEventResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceEventResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServiceEventResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ServiceEventResponse) SetId(v string) {
	o.Id = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *ServiceEventResponse) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceEventResponse) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *ServiceEventResponse) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *ServiceEventResponse) SetSummary(v string) {
	o.Summary = &v
}

// GetImpact returns the Impact field value if set, zero value otherwise.
func (o *ServiceEventResponse) GetImpact() string {
	if o == nil || IsNil(o.Impact) {
		var ret string
		return ret
	}
	return *o.Impact
}

// GetImpactOk returns a tuple with the Impact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceEventResponse) GetImpactOk() (*string, bool) {
	if o == nil || IsNil(o.Impact) {
		return nil, false
	}
	return o.Impact, true
}

// HasImpact returns a boolean if a field has been set.
func (o *ServiceEventResponse) HasImpact() bool {
	if o != nil && !IsNil(o.Impact) {
		return true
	}

	return false
}

// SetImpact gets a reference to the given string and assigns it to the Impact field.
func (o *ServiceEventResponse) SetImpact(v string) {
	o.Impact = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ServiceEventResponse) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceEventResponse) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ServiceEventResponse) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ServiceEventResponse) SetState(v string) {
	o.State = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *ServiceEventResponse) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceEventResponse) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *ServiceEventResponse) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *ServiceEventResponse) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

// GetEstimatedResolutionAt returns the EstimatedResolutionAt field value if set, zero value otherwise.
func (o *ServiceEventResponse) GetEstimatedResolutionAt() time.Time {
	if o == nil || IsNil(o.EstimatedResolutionAt) {
		var ret time.Time
		return ret
	}
	return *o.EstimatedResolutionAt
}

// GetEstimatedResolutionAtOk returns a tuple with the EstimatedResolutionAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceEventResponse) GetEstimatedResolutionAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EstimatedResolutionAt) {
		return nil, false
	}
	return o.EstimatedResolutionAt, true
}

// HasEstimatedResolutionAt returns a boolean if a field has been set.
func (o *ServiceEventResponse) HasEstimatedResolutionAt() bool {
	if o != nil && !IsNil(o.EstimatedResolutionAt) {
		return true
	}

	return false
}

// SetEstimatedResolutionAt gets a reference to the given time.Time and assigns it to the EstimatedResolutionAt field.
func (o *ServiceEventResponse) SetEstimatedResolutionAt(v time.Time) {
	o.EstimatedResolutionAt = &v
}

// GetResolvedAt returns the ResolvedAt field value if set, zero value otherwise.
func (o *ServiceEventResponse) GetResolvedAt() time.Time {
	if o == nil || IsNil(o.ResolvedAt) {
		var ret time.Time
		return ret
	}
	return *o.ResolvedAt
}

// GetResolvedAtOk returns a tuple with the ResolvedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceEventResponse) GetResolvedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ResolvedAt) {
		return nil, false
	}
	return o.ResolvedAt, true
}

// HasResolvedAt returns a boolean if a field has been set.
func (o *ServiceEventResponse) HasResolvedAt() bool {
	if o != nil && !IsNil(o.ResolvedAt) {
		return true
	}

	return false
}

// SetResolvedAt gets a reference to the given time.Time and assigns it to the ResolvedAt field.
func (o *ServiceEventResponse) SetResolvedAt(v time.Time) {
	o.ResolvedAt = &v
}

// GetDowntimeExcluded returns the DowntimeExcluded field value if set, zero value otherwise.
func (o *ServiceEventResponse) GetDowntimeExcluded() bool {
	if o == nil || IsNil(o.DowntimeExcluded) {
		var ret bool
		return ret
	}
	return *o.DowntimeExcluded
}

// GetDowntimeExcludedOk returns a tuple with the DowntimeExcluded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceEventResponse) GetDowntimeExcludedOk() (*bool, bool) {
	if o == nil || IsNil(o.DowntimeExcluded) {
		return nil, false
	}
	return o.DowntimeExcluded, true
}

// HasDowntimeExcluded returns a boolean if a field has been set.
func (o *ServiceEventResponse) HasDowntimeExcluded() bool {
	if o != nil && !IsNil(o.DowntimeExcluded) {
		return true
	}

	return false
}

// SetDowntimeExcluded gets a reference to the given bool and assigns it to the DowntimeExcluded field.
func (o *ServiceEventResponse) SetDowntimeExcluded(v bool) {
	o.DowntimeExcluded = &v
}

func (o ServiceEventResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceEventResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Impact) {
		toSerialize["impact"] = o.Impact
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	if !IsNil(o.EstimatedResolutionAt) {
		toSerialize["estimated_resolution_at"] = o.EstimatedResolutionAt
	}
	if !IsNil(o.ResolvedAt) {
		toSerialize["resolved_at"] = o.ResolvedAt
	}
	if !IsNil(o.DowntimeExcluded) {
		toSerialize["downtime_excluded"] = o.DowntimeExcluded
	}
	return toSerialize, nil
}

type NullableServiceEventResponse struct {
	value *ServiceEventResponse
	isSet bool
}

func (v NullableServiceEventResponse) Get() *ServiceEventResponse {
	return v.value
}

func (v *NullableServiceEventResponse) Set(val *ServiceEventResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceEventResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceEventResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceEventResponse(val *ServiceEventResponse) *NullableServiceEventResponse {
	return &NullableServiceEventResponse{value: val, isSet: true}
}

func (v NullableServiceEventResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceEventResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
