/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the QuotaInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuotaInfo{}

// QuotaInfo Quota limits and current usage for a tenant.
type QuotaInfo struct {
	TenantId *string               `json:"tenant_id,omitempty"`
	Quotas   map[string]QuotaLimit `json:"quotas,omitempty"`
}

// NewQuotaInfo instantiates a new QuotaInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaInfo() *QuotaInfo {
	this := QuotaInfo{}
	return &this
}

// NewQuotaInfoWithDefaults instantiates a new QuotaInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaInfoWithDefaults() *QuotaInfo {
	this := QuotaInfo{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *QuotaInfo) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaInfo) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *QuotaInfo) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *QuotaInfo) SetTenantId(v string) {
	o.TenantId = &v
}

// GetQuotas returns the Quotas field value if set, zero value otherwise.
func (o *QuotaInfo) GetQuotas() map[string]QuotaLimit {
	if o == nil || IsNil(o.Quotas) {
		var ret map[string]QuotaLimit
		return ret
	}
	return o.Quotas
}

// GetQuotasOk returns a tuple with the Quotas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaInfo) GetQuotasOk() (map[string]QuotaLimit, bool) {
	if o == nil || IsNil(o.Quotas) {
		return map[string]QuotaLimit{}, false
	}
	return o.Quotas, true
}

// HasQuotas returns a boolean if a field has been set.
func (o *QuotaInfo) HasQuotas() bool {
	if o != nil && !IsNil(o.Quotas) {
		return true
	}

	return false
}

// SetQuotas gets a reference to the given map[string]QuotaLimit and assigns it to the Quotas field.
func (o *QuotaInfo) SetQuotas(v map[string]QuotaLimit) {
	o.Quotas = v
}

func (o QuotaInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuotaInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.Quotas) {
		toSerialize["quotas"] = o.Quotas
	}
	return toSerialize, nil
}

type NullableQuotaInfo struct {
	value *QuotaInfo
	isSet bool
}

func (v NullableQuotaInfo) Get() *QuotaInfo {
	return v.value
}

func (v *NullableQuotaInfo) Set(val *QuotaInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaInfo(val *QuotaInfo) *NullableQuotaInfo {
	return &NullableQuotaInfo{value: val, isSet: true}
}

func (v NullableQuotaInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
