/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the UsageCostSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageCostSummary{}

// UsageCostSummary struct for UsageCostSummary
type UsageCostSummary struct {
	TenantId  *string               `json:"tenant_id,omitempty"`
	Period    *string               `json:"period,omitempty"`
	Metrics   map[string]float32    `json:"metrics,omitempty"`
	Costs     map[string]CostDetail `json:"costs,omitempty"`
	TotalCost *float32              `json:"total_cost,omitempty"`
	Currency  *string               `json:"currency,omitempty"`
}

// NewUsageCostSummary instantiates a new UsageCostSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageCostSummary() *UsageCostSummary {
	this := UsageCostSummary{}
	return &this
}

// NewUsageCostSummaryWithDefaults instantiates a new UsageCostSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageCostSummaryWithDefaults() *UsageCostSummary {
	this := UsageCostSummary{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *UsageCostSummary) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageCostSummary) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *UsageCostSummary) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *UsageCostSummary) SetTenantId(v string) {
	o.TenantId = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *UsageCostSummary) GetPeriod() string {
	if o == nil || IsNil(o.Period) {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageCostSummary) GetPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *UsageCostSummary) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *UsageCostSummary) SetPeriod(v string) {
	o.Period = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *UsageCostSummary) GetMetrics() map[string]float32 {
	if o == nil || IsNil(o.Metrics) {
		var ret map[string]float32
		return ret
	}
	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageCostSummary) GetMetricsOk() (map[string]float32, bool) {
	if o == nil || IsNil(o.Metrics) {
		return map[string]float32{}, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *UsageCostSummary) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given map[string]float32 and assigns it to the Metrics field.
func (o *UsageCostSummary) SetMetrics(v map[string]float32) {
	o.Metrics = v
}

// GetCosts returns the Costs field value if set, zero value otherwise.
func (o *UsageCostSummary) GetCosts() map[string]CostDetail {
	if o == nil || IsNil(o.Costs) {
		var ret map[string]CostDetail
		return ret
	}
	return o.Costs
}

// GetCostsOk returns a tuple with the Costs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageCostSummary) GetCostsOk() (map[string]CostDetail, bool) {
	if o == nil || IsNil(o.Costs) {
		return map[string]CostDetail{}, false
	}
	return o.Costs, true
}

// HasCosts returns a boolean if a field has been set.
func (o *UsageCostSummary) HasCosts() bool {
	if o != nil && !IsNil(o.Costs) {
		return true
	}

	return false
}

// SetCosts gets a reference to the given map[string]CostDetail and assigns it to the Costs field.
func (o *UsageCostSummary) SetCosts(v map[string]CostDetail) {
	o.Costs = v
}

// GetTotalCost returns the TotalCost field value if set, zero value otherwise.
func (o *UsageCostSummary) GetTotalCost() float32 {
	if o == nil || IsNil(o.TotalCost) {
		var ret float32
		return ret
	}
	return *o.TotalCost
}

// GetTotalCostOk returns a tuple with the TotalCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageCostSummary) GetTotalCostOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalCost) {
		return nil, false
	}
	return o.TotalCost, true
}

// HasTotalCost returns a boolean if a field has been set.
func (o *UsageCostSummary) HasTotalCost() bool {
	if o != nil && !IsNil(o.TotalCost) {
		return true
	}

	return false
}

// SetTotalCost gets a reference to the given float32 and assigns it to the TotalCost field.
func (o *UsageCostSummary) SetTotalCost(v float32) {
	o.TotalCost = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *UsageCostSummary) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageCostSummary) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *UsageCostSummary) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *UsageCostSummary) SetCurrency(v string) {
	o.Currency = &v
}

func (o UsageCostSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageCostSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	if !IsNil(o.Costs) {
		toSerialize["costs"] = o.Costs
	}
	if !IsNil(o.TotalCost) {
		toSerialize["total_cost"] = o.TotalCost
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullableUsageCostSummary struct {
	value *UsageCostSummary
	isSet bool
}

func (v NullableUsageCostSummary) Get() *UsageCostSummary {
	return v.value
}

func (v *NullableUsageCostSummary) Set(val *UsageCostSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageCostSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageCostSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageCostSummary(val *UsageCostSummary) *NullableUsageCostSummary {
	return &NullableUsageCostSummary{value: val, isSet: true}
}

func (v NullableUsageCostSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageCostSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
