/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the FaultSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FaultSummary{}

// FaultSummary Aggregated fault counts by severity, component, state, and site.
type FaultSummary struct {
	BySeverity  map[string]int32   `json:"by_severity,omitempty"`
	ByComponent map[string]int32   `json:"by_component,omitempty"`
	ByState     map[string]int32   `json:"by_state,omitempty"`
	BySite      []SiteFaultSummary `json:"by_site,omitempty"`
}

// NewFaultSummary instantiates a new FaultSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFaultSummary() *FaultSummary {
	this := FaultSummary{}
	return &this
}

// NewFaultSummaryWithDefaults instantiates a new FaultSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFaultSummaryWithDefaults() *FaultSummary {
	this := FaultSummary{}
	return &this
}

// GetBySeverity returns the BySeverity field value if set, zero value otherwise.
func (o *FaultSummary) GetBySeverity() map[string]int32 {
	if o == nil || IsNil(o.BySeverity) {
		var ret map[string]int32
		return ret
	}
	return o.BySeverity
}

// GetBySeverityOk returns a tuple with the BySeverity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultSummary) GetBySeverityOk() (map[string]int32, bool) {
	if o == nil || IsNil(o.BySeverity) {
		return map[string]int32{}, false
	}
	return o.BySeverity, true
}

// HasBySeverity returns a boolean if a field has been set.
func (o *FaultSummary) HasBySeverity() bool {
	if o != nil && !IsNil(o.BySeverity) {
		return true
	}

	return false
}

// SetBySeverity gets a reference to the given map[string]int32 and assigns it to the BySeverity field.
func (o *FaultSummary) SetBySeverity(v map[string]int32) {
	o.BySeverity = v
}

// GetByComponent returns the ByComponent field value if set, zero value otherwise.
func (o *FaultSummary) GetByComponent() map[string]int32 {
	if o == nil || IsNil(o.ByComponent) {
		var ret map[string]int32
		return ret
	}
	return o.ByComponent
}

// GetByComponentOk returns a tuple with the ByComponent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultSummary) GetByComponentOk() (map[string]int32, bool) {
	if o == nil || IsNil(o.ByComponent) {
		return map[string]int32{}, false
	}
	return o.ByComponent, true
}

// HasByComponent returns a boolean if a field has been set.
func (o *FaultSummary) HasByComponent() bool {
	if o != nil && !IsNil(o.ByComponent) {
		return true
	}

	return false
}

// SetByComponent gets a reference to the given map[string]int32 and assigns it to the ByComponent field.
func (o *FaultSummary) SetByComponent(v map[string]int32) {
	o.ByComponent = v
}

// GetByState returns the ByState field value if set, zero value otherwise.
func (o *FaultSummary) GetByState() map[string]int32 {
	if o == nil || IsNil(o.ByState) {
		var ret map[string]int32
		return ret
	}
	return o.ByState
}

// GetByStateOk returns a tuple with the ByState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultSummary) GetByStateOk() (map[string]int32, bool) {
	if o == nil || IsNil(o.ByState) {
		return map[string]int32{}, false
	}
	return o.ByState, true
}

// HasByState returns a boolean if a field has been set.
func (o *FaultSummary) HasByState() bool {
	if o != nil && !IsNil(o.ByState) {
		return true
	}

	return false
}

// SetByState gets a reference to the given map[string]int32 and assigns it to the ByState field.
func (o *FaultSummary) SetByState(v map[string]int32) {
	o.ByState = v
}

// GetBySite returns the BySite field value if set, zero value otherwise.
func (o *FaultSummary) GetBySite() []SiteFaultSummary {
	if o == nil || IsNil(o.BySite) {
		var ret []SiteFaultSummary
		return ret
	}
	return o.BySite
}

// GetBySiteOk returns a tuple with the BySite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultSummary) GetBySiteOk() ([]SiteFaultSummary, bool) {
	if o == nil || IsNil(o.BySite) {
		return nil, false
	}
	return o.BySite, true
}

// HasBySite returns a boolean if a field has been set.
func (o *FaultSummary) HasBySite() bool {
	if o != nil && !IsNil(o.BySite) {
		return true
	}

	return false
}

// SetBySite gets a reference to the given []SiteFaultSummary and assigns it to the BySite field.
func (o *FaultSummary) SetBySite(v []SiteFaultSummary) {
	o.BySite = v
}

func (o FaultSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FaultSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BySeverity) {
		toSerialize["by_severity"] = o.BySeverity
	}
	if !IsNil(o.ByComponent) {
		toSerialize["by_component"] = o.ByComponent
	}
	if !IsNil(o.ByState) {
		toSerialize["by_state"] = o.ByState
	}
	if !IsNil(o.BySite) {
		toSerialize["by_site"] = o.BySite
	}
	return toSerialize, nil
}

type NullableFaultSummary struct {
	value *FaultSummary
	isSet bool
}

func (v NullableFaultSummary) Get() *FaultSummary {
	return v.value
}

func (v *NullableFaultSummary) Set(val *FaultSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableFaultSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableFaultSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFaultSummary(val *FaultSummary) *NullableFaultSummary {
	return &NullableFaultSummary{value: val, isSet: true}
}

func (v NullableFaultSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFaultSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
