/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the BlueprintResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintResource{}

// BlueprintResource struct for BlueprintResource
type BlueprintResource struct {
	Type       *string                `json:"type,omitempty"`
	DependsOn  []string               `json:"depends_on,omitempty"`
	Condition  *string                `json:"condition,omitempty"`
	Count      *string                `json:"count,omitempty"`
	Properties map[string]interface{} `json:"properties,omitempty"`
}

// NewBlueprintResource instantiates a new BlueprintResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintResource() *BlueprintResource {
	this := BlueprintResource{}
	return &this
}

// NewBlueprintResourceWithDefaults instantiates a new BlueprintResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintResourceWithDefaults() *BlueprintResource {
	this := BlueprintResource{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *BlueprintResource) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintResource) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *BlueprintResource) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *BlueprintResource) SetType(v string) {
	o.Type = &v
}

// GetDependsOn returns the DependsOn field value if set, zero value otherwise.
func (o *BlueprintResource) GetDependsOn() []string {
	if o == nil || IsNil(o.DependsOn) {
		var ret []string
		return ret
	}
	return o.DependsOn
}

// GetDependsOnOk returns a tuple with the DependsOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintResource) GetDependsOnOk() ([]string, bool) {
	if o == nil || IsNil(o.DependsOn) {
		return nil, false
	}
	return o.DependsOn, true
}

// HasDependsOn returns a boolean if a field has been set.
func (o *BlueprintResource) HasDependsOn() bool {
	if o != nil && !IsNil(o.DependsOn) {
		return true
	}

	return false
}

// SetDependsOn gets a reference to the given []string and assigns it to the DependsOn field.
func (o *BlueprintResource) SetDependsOn(v []string) {
	o.DependsOn = v
}

// GetCondition returns the Condition field value if set, zero value otherwise.
func (o *BlueprintResource) GetCondition() string {
	if o == nil || IsNil(o.Condition) {
		var ret string
		return ret
	}
	return *o.Condition
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintResource) GetConditionOk() (*string, bool) {
	if o == nil || IsNil(o.Condition) {
		return nil, false
	}
	return o.Condition, true
}

// HasCondition returns a boolean if a field has been set.
func (o *BlueprintResource) HasCondition() bool {
	if o != nil && !IsNil(o.Condition) {
		return true
	}

	return false
}

// SetCondition gets a reference to the given string and assigns it to the Condition field.
func (o *BlueprintResource) SetCondition(v string) {
	o.Condition = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *BlueprintResource) GetCount() string {
	if o == nil || IsNil(o.Count) {
		var ret string
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintResource) GetCountOk() (*string, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *BlueprintResource) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given string and assigns it to the Count field.
func (o *BlueprintResource) SetCount(v string) {
	o.Count = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *BlueprintResource) GetProperties() map[string]interface{} {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]interface{}
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintResource) GetPropertiesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Properties) {
		return map[string]interface{}{}, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *BlueprintResource) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]interface{} and assigns it to the Properties field.
func (o *BlueprintResource) SetProperties(v map[string]interface{}) {
	o.Properties = v
}

func (o BlueprintResource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.DependsOn) {
		toSerialize["depends_on"] = o.DependsOn
	}
	if !IsNil(o.Condition) {
		toSerialize["condition"] = o.Condition
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

type NullableBlueprintResource struct {
	value *BlueprintResource
	isSet bool
}

func (v NullableBlueprintResource) Get() *BlueprintResource {
	return v.value
}

func (v *NullableBlueprintResource) Set(val *BlueprintResource) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintResource) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintResource(val *BlueprintResource) *NullableBlueprintResource {
	return &NullableBlueprintResource{value: val, isSet: true}
}

func (v NullableBlueprintResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
