/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the CostEstimateBreakdownInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CostEstimateBreakdownInner{}

// CostEstimateBreakdownInner struct for CostEstimateBreakdownInner
type CostEstimateBreakdownInner struct {
	Blueprint *string  `json:"blueprint,omitempty"`
	Rate      *float32 `json:"rate,omitempty"`
}

// NewCostEstimateBreakdownInner instantiates a new CostEstimateBreakdownInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCostEstimateBreakdownInner() *CostEstimateBreakdownInner {
	this := CostEstimateBreakdownInner{}
	return &this
}

// NewCostEstimateBreakdownInnerWithDefaults instantiates a new CostEstimateBreakdownInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCostEstimateBreakdownInnerWithDefaults() *CostEstimateBreakdownInner {
	this := CostEstimateBreakdownInner{}
	return &this
}

// GetBlueprint returns the Blueprint field value if set, zero value otherwise.
func (o *CostEstimateBreakdownInner) GetBlueprint() string {
	if o == nil || IsNil(o.Blueprint) {
		var ret string
		return ret
	}
	return *o.Blueprint
}

// GetBlueprintOk returns a tuple with the Blueprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostEstimateBreakdownInner) GetBlueprintOk() (*string, bool) {
	if o == nil || IsNil(o.Blueprint) {
		return nil, false
	}
	return o.Blueprint, true
}

// HasBlueprint returns a boolean if a field has been set.
func (o *CostEstimateBreakdownInner) HasBlueprint() bool {
	if o != nil && !IsNil(o.Blueprint) {
		return true
	}

	return false
}

// SetBlueprint gets a reference to the given string and assigns it to the Blueprint field.
func (o *CostEstimateBreakdownInner) SetBlueprint(v string) {
	o.Blueprint = &v
}

// GetRate returns the Rate field value if set, zero value otherwise.
func (o *CostEstimateBreakdownInner) GetRate() float32 {
	if o == nil || IsNil(o.Rate) {
		var ret float32
		return ret
	}
	return *o.Rate
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostEstimateBreakdownInner) GetRateOk() (*float32, bool) {
	if o == nil || IsNil(o.Rate) {
		return nil, false
	}
	return o.Rate, true
}

// HasRate returns a boolean if a field has been set.
func (o *CostEstimateBreakdownInner) HasRate() bool {
	if o != nil && !IsNil(o.Rate) {
		return true
	}

	return false
}

// SetRate gets a reference to the given float32 and assigns it to the Rate field.
func (o *CostEstimateBreakdownInner) SetRate(v float32) {
	o.Rate = &v
}

func (o CostEstimateBreakdownInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CostEstimateBreakdownInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Blueprint) {
		toSerialize["blueprint"] = o.Blueprint
	}
	if !IsNil(o.Rate) {
		toSerialize["rate"] = o.Rate
	}
	return toSerialize, nil
}

type NullableCostEstimateBreakdownInner struct {
	value *CostEstimateBreakdownInner
	isSet bool
}

func (v NullableCostEstimateBreakdownInner) Get() *CostEstimateBreakdownInner {
	return v.value
}

func (v *NullableCostEstimateBreakdownInner) Set(val *CostEstimateBreakdownInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCostEstimateBreakdownInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCostEstimateBreakdownInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCostEstimateBreakdownInner(val *CostEstimateBreakdownInner) *NullableCostEstimateBreakdownInner {
	return &NullableCostEstimateBreakdownInner{value: val, isSet: true}
}

func (v NullableCostEstimateBreakdownInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCostEstimateBreakdownInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
