/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the QuotaLimit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuotaLimit{}

// QuotaLimit A single quota with its limit and current usage.
type QuotaLimit struct {
	Limit   *float32 `json:"limit,omitempty"`
	Current *float32 `json:"current,omitempty"`
	Unit    *string  `json:"unit,omitempty"`
}

// NewQuotaLimit instantiates a new QuotaLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaLimit() *QuotaLimit {
	this := QuotaLimit{}
	return &this
}

// NewQuotaLimitWithDefaults instantiates a new QuotaLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaLimitWithDefaults() *QuotaLimit {
	this := QuotaLimit{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *QuotaLimit) GetLimit() float32 {
	if o == nil || IsNil(o.Limit) {
		var ret float32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaLimit) GetLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *QuotaLimit) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given float32 and assigns it to the Limit field.
func (o *QuotaLimit) SetLimit(v float32) {
	o.Limit = &v
}

// GetCurrent returns the Current field value if set, zero value otherwise.
func (o *QuotaLimit) GetCurrent() float32 {
	if o == nil || IsNil(o.Current) {
		var ret float32
		return ret
	}
	return *o.Current
}

// GetCurrentOk returns a tuple with the Current field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaLimit) GetCurrentOk() (*float32, bool) {
	if o == nil || IsNil(o.Current) {
		return nil, false
	}
	return o.Current, true
}

// HasCurrent returns a boolean if a field has been set.
func (o *QuotaLimit) HasCurrent() bool {
	if o != nil && !IsNil(o.Current) {
		return true
	}

	return false
}

// SetCurrent gets a reference to the given float32 and assigns it to the Current field.
func (o *QuotaLimit) SetCurrent(v float32) {
	o.Current = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *QuotaLimit) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaLimit) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *QuotaLimit) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *QuotaLimit) SetUnit(v string) {
	o.Unit = &v
}

func (o QuotaLimit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuotaLimit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Current) {
		toSerialize["current"] = o.Current
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	return toSerialize, nil
}

type NullableQuotaLimit struct {
	value *QuotaLimit
	isSet bool
}

func (v NullableQuotaLimit) Get() *QuotaLimit {
	return v.value
}

func (v *NullableQuotaLimit) Set(val *QuotaLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaLimit(val *QuotaLimit) *NullableQuotaLimit {
	return &NullableQuotaLimit{value: val, isSet: true}
}

func (v NullableQuotaLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
