/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the CostEstimate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CostEstimate{}

// CostEstimate struct for CostEstimate
type CostEstimate struct {
	EstimatedRate *float32                     `json:"estimated_rate,omitempty"`
	Unit          *string                      `json:"unit,omitempty"`
	Currency      *string                      `json:"currency,omitempty"`
	Breakdown     []CostEstimateBreakdownInner `json:"breakdown,omitempty"`
}

// NewCostEstimate instantiates a new CostEstimate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCostEstimate() *CostEstimate {
	this := CostEstimate{}
	return &this
}

// NewCostEstimateWithDefaults instantiates a new CostEstimate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCostEstimateWithDefaults() *CostEstimate {
	this := CostEstimate{}
	return &this
}

// GetEstimatedRate returns the EstimatedRate field value if set, zero value otherwise.
func (o *CostEstimate) GetEstimatedRate() float32 {
	if o == nil || IsNil(o.EstimatedRate) {
		var ret float32
		return ret
	}
	return *o.EstimatedRate
}

// GetEstimatedRateOk returns a tuple with the EstimatedRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostEstimate) GetEstimatedRateOk() (*float32, bool) {
	if o == nil || IsNil(o.EstimatedRate) {
		return nil, false
	}
	return o.EstimatedRate, true
}

// HasEstimatedRate returns a boolean if a field has been set.
func (o *CostEstimate) HasEstimatedRate() bool {
	if o != nil && !IsNil(o.EstimatedRate) {
		return true
	}

	return false
}

// SetEstimatedRate gets a reference to the given float32 and assigns it to the EstimatedRate field.
func (o *CostEstimate) SetEstimatedRate(v float32) {
	o.EstimatedRate = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *CostEstimate) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostEstimate) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *CostEstimate) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *CostEstimate) SetUnit(v string) {
	o.Unit = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *CostEstimate) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostEstimate) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *CostEstimate) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *CostEstimate) SetCurrency(v string) {
	o.Currency = &v
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise.
func (o *CostEstimate) GetBreakdown() []CostEstimateBreakdownInner {
	if o == nil || IsNil(o.Breakdown) {
		var ret []CostEstimateBreakdownInner
		return ret
	}
	return o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostEstimate) GetBreakdownOk() ([]CostEstimateBreakdownInner, bool) {
	if o == nil || IsNil(o.Breakdown) {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *CostEstimate) HasBreakdown() bool {
	if o != nil && !IsNil(o.Breakdown) {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given []CostEstimateBreakdownInner and assigns it to the Breakdown field.
func (o *CostEstimate) SetBreakdown(v []CostEstimateBreakdownInner) {
	o.Breakdown = v
}

func (o CostEstimate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CostEstimate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EstimatedRate) {
		toSerialize["estimated_rate"] = o.EstimatedRate
	}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Breakdown) {
		toSerialize["breakdown"] = o.Breakdown
	}
	return toSerialize, nil
}

type NullableCostEstimate struct {
	value *CostEstimate
	isSet bool
}

func (v NullableCostEstimate) Get() *CostEstimate {
	return v.value
}

func (v *NullableCostEstimate) Set(val *CostEstimate) {
	v.value = val
	v.isSet = true
}

func (v NullableCostEstimate) IsSet() bool {
	return v.isSet
}

func (v *NullableCostEstimate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCostEstimate(val *CostEstimate) *NullableCostEstimate {
	return &NullableCostEstimate{value: val, isSet: true}
}

func (v NullableCostEstimate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCostEstimate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
