/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the ListResourceTypes200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListResourceTypes200Response{}

// ListResourceTypes200Response struct for ListResourceTypes200Response
type ListResourceTypes200Response struct {
	ResourceTypes []string `json:"resource_types,omitempty"`
}

// NewListResourceTypes200Response instantiates a new ListResourceTypes200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListResourceTypes200Response() *ListResourceTypes200Response {
	this := ListResourceTypes200Response{}
	return &this
}

// NewListResourceTypes200ResponseWithDefaults instantiates a new ListResourceTypes200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListResourceTypes200ResponseWithDefaults() *ListResourceTypes200Response {
	this := ListResourceTypes200Response{}
	return &this
}

// GetResourceTypes returns the ResourceTypes field value if set, zero value otherwise.
func (o *ListResourceTypes200Response) GetResourceTypes() []string {
	if o == nil || IsNil(o.ResourceTypes) {
		var ret []string
		return ret
	}
	return o.ResourceTypes
}

// GetResourceTypesOk returns a tuple with the ResourceTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListResourceTypes200Response) GetResourceTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.ResourceTypes) {
		return nil, false
	}
	return o.ResourceTypes, true
}

// HasResourceTypes returns a boolean if a field has been set.
func (o *ListResourceTypes200Response) HasResourceTypes() bool {
	if o != nil && !IsNil(o.ResourceTypes) {
		return true
	}

	return false
}

// SetResourceTypes gets a reference to the given []string and assigns it to the ResourceTypes field.
func (o *ListResourceTypes200Response) SetResourceTypes(v []string) {
	o.ResourceTypes = v
}

func (o ListResourceTypes200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListResourceTypes200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ResourceTypes) {
		toSerialize["resource_types"] = o.ResourceTypes
	}
	return toSerialize, nil
}

type NullableListResourceTypes200Response struct {
	value *ListResourceTypes200Response
	isSet bool
}

func (v NullableListResourceTypes200Response) Get() *ListResourceTypes200Response {
	return v.value
}

func (v *NullableListResourceTypes200Response) Set(val *ListResourceTypes200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListResourceTypes200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListResourceTypes200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListResourceTypes200Response(val *ListResourceTypes200Response) *NullableListResourceTypes200Response {
	return &NullableListResourceTypes200Response{value: val, isSet: true}
}

func (v NullableListResourceTypes200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListResourceTypes200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
