/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateBlueprintRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBlueprintRequest{}

// CreateBlueprintRequest struct for CreateBlueprintRequest
type CreateBlueprintRequest struct {
	Name        string                        `json:"name"`
	Version     string                        `json:"version"`
	Description *string                       `json:"description,omitempty"`
	Parameters  map[string]BlueprintParameter `json:"parameters,omitempty"`
	Resources   map[string]BlueprintResource  `json:"resources,omitempty"`
	Labels      map[string]string             `json:"labels,omitempty"`
	Pricing     *PricingSpec                  `json:"pricing,omitempty"`
	TenantId    *string                       `json:"tenant_id,omitempty"`
	Visibility  *string                       `json:"visibility,omitempty"`
	BasedOn     *string                       `json:"based_on,omitempty"`
}

type _CreateBlueprintRequest CreateBlueprintRequest

// NewCreateBlueprintRequest instantiates a new CreateBlueprintRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBlueprintRequest(name string, version string) *CreateBlueprintRequest {
	this := CreateBlueprintRequest{}
	this.Name = name
	this.Version = version
	return &this
}

// NewCreateBlueprintRequestWithDefaults instantiates a new CreateBlueprintRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBlueprintRequestWithDefaults() *CreateBlueprintRequest {
	this := CreateBlueprintRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateBlueprintRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateBlueprintRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateBlueprintRequest) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *CreateBlueprintRequest) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CreateBlueprintRequest) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CreateBlueprintRequest) SetVersion(v string) {
	o.Version = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateBlueprintRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlueprintRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateBlueprintRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateBlueprintRequest) SetDescription(v string) {
	o.Description = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *CreateBlueprintRequest) GetParameters() map[string]BlueprintParameter {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]BlueprintParameter
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlueprintRequest) GetParametersOk() (map[string]BlueprintParameter, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]BlueprintParameter{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *CreateBlueprintRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]BlueprintParameter and assigns it to the Parameters field.
func (o *CreateBlueprintRequest) SetParameters(v map[string]BlueprintParameter) {
	o.Parameters = v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *CreateBlueprintRequest) GetResources() map[string]BlueprintResource {
	if o == nil || IsNil(o.Resources) {
		var ret map[string]BlueprintResource
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlueprintRequest) GetResourcesOk() (map[string]BlueprintResource, bool) {
	if o == nil || IsNil(o.Resources) {
		return map[string]BlueprintResource{}, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *CreateBlueprintRequest) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given map[string]BlueprintResource and assigns it to the Resources field.
func (o *CreateBlueprintRequest) SetResources(v map[string]BlueprintResource) {
	o.Resources = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateBlueprintRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlueprintRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CreateBlueprintRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *CreateBlueprintRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetPricing returns the Pricing field value if set, zero value otherwise.
func (o *CreateBlueprintRequest) GetPricing() PricingSpec {
	if o == nil || IsNil(o.Pricing) {
		var ret PricingSpec
		return ret
	}
	return *o.Pricing
}

// GetPricingOk returns a tuple with the Pricing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlueprintRequest) GetPricingOk() (*PricingSpec, bool) {
	if o == nil || IsNil(o.Pricing) {
		return nil, false
	}
	return o.Pricing, true
}

// HasPricing returns a boolean if a field has been set.
func (o *CreateBlueprintRequest) HasPricing() bool {
	if o != nil && !IsNil(o.Pricing) {
		return true
	}

	return false
}

// SetPricing gets a reference to the given PricingSpec and assigns it to the Pricing field.
func (o *CreateBlueprintRequest) SetPricing(v PricingSpec) {
	o.Pricing = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CreateBlueprintRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlueprintRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CreateBlueprintRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CreateBlueprintRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetVisibility returns the Visibility field value if set, zero value otherwise.
func (o *CreateBlueprintRequest) GetVisibility() string {
	if o == nil || IsNil(o.Visibility) {
		var ret string
		return ret
	}
	return *o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlueprintRequest) GetVisibilityOk() (*string, bool) {
	if o == nil || IsNil(o.Visibility) {
		return nil, false
	}
	return o.Visibility, true
}

// HasVisibility returns a boolean if a field has been set.
func (o *CreateBlueprintRequest) HasVisibility() bool {
	if o != nil && !IsNil(o.Visibility) {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given string and assigns it to the Visibility field.
func (o *CreateBlueprintRequest) SetVisibility(v string) {
	o.Visibility = &v
}

// GetBasedOn returns the BasedOn field value if set, zero value otherwise.
func (o *CreateBlueprintRequest) GetBasedOn() string {
	if o == nil || IsNil(o.BasedOn) {
		var ret string
		return ret
	}
	return *o.BasedOn
}

// GetBasedOnOk returns a tuple with the BasedOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBlueprintRequest) GetBasedOnOk() (*string, bool) {
	if o == nil || IsNil(o.BasedOn) {
		return nil, false
	}
	return o.BasedOn, true
}

// HasBasedOn returns a boolean if a field has been set.
func (o *CreateBlueprintRequest) HasBasedOn() bool {
	if o != nil && !IsNil(o.BasedOn) {
		return true
	}

	return false
}

// SetBasedOn gets a reference to the given string and assigns it to the BasedOn field.
func (o *CreateBlueprintRequest) SetBasedOn(v string) {
	o.BasedOn = &v
}

func (o CreateBlueprintRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBlueprintRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Pricing) {
		toSerialize["pricing"] = o.Pricing
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.Visibility) {
		toSerialize["visibility"] = o.Visibility
	}
	if !IsNil(o.BasedOn) {
		toSerialize["based_on"] = o.BasedOn
	}
	return toSerialize, nil
}

func (o *CreateBlueprintRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBlueprintRequest := _CreateBlueprintRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBlueprintRequest)

	if err != nil {
		return err
	}

	*o = CreateBlueprintRequest(varCreateBlueprintRequest)

	return err
}

type NullableCreateBlueprintRequest struct {
	value *CreateBlueprintRequest
	isSet bool
}

func (v NullableCreateBlueprintRequest) Get() *CreateBlueprintRequest {
	return v.value
}

func (v *NullableCreateBlueprintRequest) Set(val *CreateBlueprintRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBlueprintRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBlueprintRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBlueprintRequest(val *CreateBlueprintRequest) *NullableCreateBlueprintRequest {
	return &NullableCreateBlueprintRequest{value: val, isSet: true}
}

func (v NullableCreateBlueprintRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBlueprintRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
