/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the UpdateBlueprintRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateBlueprintRequest{}

// UpdateBlueprintRequest struct for UpdateBlueprintRequest
type UpdateBlueprintRequest struct {
	Name        *string                       `json:"name,omitempty"`
	Version     *string                       `json:"version,omitempty"`
	Description *string                       `json:"description,omitempty"`
	Parameters  map[string]BlueprintParameter `json:"parameters,omitempty"`
	Resources   map[string]BlueprintResource  `json:"resources,omitempty"`
	Labels      map[string]string             `json:"labels,omitempty"`
	Pricing     *PricingSpec                  `json:"pricing,omitempty"`
	Visibility  *string                       `json:"visibility,omitempty"`
}

// NewUpdateBlueprintRequest instantiates a new UpdateBlueprintRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateBlueprintRequest() *UpdateBlueprintRequest {
	this := UpdateBlueprintRequest{}
	return &this
}

// NewUpdateBlueprintRequestWithDefaults instantiates a new UpdateBlueprintRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateBlueprintRequestWithDefaults() *UpdateBlueprintRequest {
	this := UpdateBlueprintRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateBlueprintRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBlueprintRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateBlueprintRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateBlueprintRequest) SetName(v string) {
	o.Name = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *UpdateBlueprintRequest) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBlueprintRequest) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *UpdateBlueprintRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *UpdateBlueprintRequest) SetVersion(v string) {
	o.Version = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateBlueprintRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBlueprintRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateBlueprintRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateBlueprintRequest) SetDescription(v string) {
	o.Description = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *UpdateBlueprintRequest) GetParameters() map[string]BlueprintParameter {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]BlueprintParameter
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBlueprintRequest) GetParametersOk() (map[string]BlueprintParameter, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]BlueprintParameter{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *UpdateBlueprintRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]BlueprintParameter and assigns it to the Parameters field.
func (o *UpdateBlueprintRequest) SetParameters(v map[string]BlueprintParameter) {
	o.Parameters = v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *UpdateBlueprintRequest) GetResources() map[string]BlueprintResource {
	if o == nil || IsNil(o.Resources) {
		var ret map[string]BlueprintResource
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBlueprintRequest) GetResourcesOk() (map[string]BlueprintResource, bool) {
	if o == nil || IsNil(o.Resources) {
		return map[string]BlueprintResource{}, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *UpdateBlueprintRequest) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given map[string]BlueprintResource and assigns it to the Resources field.
func (o *UpdateBlueprintRequest) SetResources(v map[string]BlueprintResource) {
	o.Resources = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *UpdateBlueprintRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBlueprintRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *UpdateBlueprintRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *UpdateBlueprintRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetPricing returns the Pricing field value if set, zero value otherwise.
func (o *UpdateBlueprintRequest) GetPricing() PricingSpec {
	if o == nil || IsNil(o.Pricing) {
		var ret PricingSpec
		return ret
	}
	return *o.Pricing
}

// GetPricingOk returns a tuple with the Pricing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBlueprintRequest) GetPricingOk() (*PricingSpec, bool) {
	if o == nil || IsNil(o.Pricing) {
		return nil, false
	}
	return o.Pricing, true
}

// HasPricing returns a boolean if a field has been set.
func (o *UpdateBlueprintRequest) HasPricing() bool {
	if o != nil && !IsNil(o.Pricing) {
		return true
	}

	return false
}

// SetPricing gets a reference to the given PricingSpec and assigns it to the Pricing field.
func (o *UpdateBlueprintRequest) SetPricing(v PricingSpec) {
	o.Pricing = &v
}

// GetVisibility returns the Visibility field value if set, zero value otherwise.
func (o *UpdateBlueprintRequest) GetVisibility() string {
	if o == nil || IsNil(o.Visibility) {
		var ret string
		return ret
	}
	return *o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBlueprintRequest) GetVisibilityOk() (*string, bool) {
	if o == nil || IsNil(o.Visibility) {
		return nil, false
	}
	return o.Visibility, true
}

// HasVisibility returns a boolean if a field has been set.
func (o *UpdateBlueprintRequest) HasVisibility() bool {
	if o != nil && !IsNil(o.Visibility) {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given string and assigns it to the Visibility field.
func (o *UpdateBlueprintRequest) SetVisibility(v string) {
	o.Visibility = &v
}

func (o UpdateBlueprintRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateBlueprintRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Pricing) {
		toSerialize["pricing"] = o.Pricing
	}
	if !IsNil(o.Visibility) {
		toSerialize["visibility"] = o.Visibility
	}
	return toSerialize, nil
}

type NullableUpdateBlueprintRequest struct {
	value *UpdateBlueprintRequest
	isSet bool
}

func (v NullableUpdateBlueprintRequest) Get() *UpdateBlueprintRequest {
	return v.value
}

func (v *NullableUpdateBlueprintRequest) Set(val *UpdateBlueprintRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateBlueprintRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateBlueprintRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateBlueprintRequest(val *UpdateBlueprintRequest) *NullableUpdateBlueprintRequest {
	return &NullableUpdateBlueprintRequest{value: val, isSet: true}
}

func (v NullableUpdateBlueprintRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateBlueprintRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
