/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the FulfillmentService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FulfillmentService{}

// FulfillmentService A provisioned tenant environment with its associated resources.
type FulfillmentService struct {
	Id            *string           `json:"id,omitempty"`
	OrderId       *string           `json:"order_id,omitempty"`
	BlueprintId   *string           `json:"blueprint_id,omitempty"`
	BlueprintName *string           `json:"blueprint_name,omitempty"`
	TenantId      *string           `json:"tenant_id,omitempty"`
	Name          *string           `json:"name,omitempty"`
	Status        *string           `json:"status,omitempty"`
	Resources     map[string]string `json:"resources,omitempty"`
	Created       *time.Time        `json:"created,omitempty"`
	Updated       *time.Time        `json:"updated,omitempty"`
}

// NewFulfillmentService instantiates a new FulfillmentService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFulfillmentService() *FulfillmentService {
	this := FulfillmentService{}
	return &this
}

// NewFulfillmentServiceWithDefaults instantiates a new FulfillmentService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFulfillmentServiceWithDefaults() *FulfillmentService {
	this := FulfillmentService{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FulfillmentService) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentService) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FulfillmentService) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FulfillmentService) SetId(v string) {
	o.Id = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *FulfillmentService) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentService) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *FulfillmentService) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *FulfillmentService) SetOrderId(v string) {
	o.OrderId = &v
}

// GetBlueprintId returns the BlueprintId field value if set, zero value otherwise.
func (o *FulfillmentService) GetBlueprintId() string {
	if o == nil || IsNil(o.BlueprintId) {
		var ret string
		return ret
	}
	return *o.BlueprintId
}

// GetBlueprintIdOk returns a tuple with the BlueprintId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentService) GetBlueprintIdOk() (*string, bool) {
	if o == nil || IsNil(o.BlueprintId) {
		return nil, false
	}
	return o.BlueprintId, true
}

// HasBlueprintId returns a boolean if a field has been set.
func (o *FulfillmentService) HasBlueprintId() bool {
	if o != nil && !IsNil(o.BlueprintId) {
		return true
	}

	return false
}

// SetBlueprintId gets a reference to the given string and assigns it to the BlueprintId field.
func (o *FulfillmentService) SetBlueprintId(v string) {
	o.BlueprintId = &v
}

// GetBlueprintName returns the BlueprintName field value if set, zero value otherwise.
func (o *FulfillmentService) GetBlueprintName() string {
	if o == nil || IsNil(o.BlueprintName) {
		var ret string
		return ret
	}
	return *o.BlueprintName
}

// GetBlueprintNameOk returns a tuple with the BlueprintName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentService) GetBlueprintNameOk() (*string, bool) {
	if o == nil || IsNil(o.BlueprintName) {
		return nil, false
	}
	return o.BlueprintName, true
}

// HasBlueprintName returns a boolean if a field has been set.
func (o *FulfillmentService) HasBlueprintName() bool {
	if o != nil && !IsNil(o.BlueprintName) {
		return true
	}

	return false
}

// SetBlueprintName gets a reference to the given string and assigns it to the BlueprintName field.
func (o *FulfillmentService) SetBlueprintName(v string) {
	o.BlueprintName = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *FulfillmentService) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentService) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *FulfillmentService) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *FulfillmentService) SetTenantId(v string) {
	o.TenantId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FulfillmentService) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentService) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FulfillmentService) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FulfillmentService) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *FulfillmentService) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentService) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *FulfillmentService) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *FulfillmentService) SetStatus(v string) {
	o.Status = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *FulfillmentService) GetResources() map[string]string {
	if o == nil || IsNil(o.Resources) {
		var ret map[string]string
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentService) GetResourcesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Resources) {
		return map[string]string{}, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *FulfillmentService) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given map[string]string and assigns it to the Resources field.
func (o *FulfillmentService) SetResources(v map[string]string) {
	o.Resources = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *FulfillmentService) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentService) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *FulfillmentService) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *FulfillmentService) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *FulfillmentService) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FulfillmentService) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *FulfillmentService) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *FulfillmentService) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o FulfillmentService) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FulfillmentService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrderId) {
		toSerialize["order_id"] = o.OrderId
	}
	if !IsNil(o.BlueprintId) {
		toSerialize["blueprint_id"] = o.BlueprintId
	}
	if !IsNil(o.BlueprintName) {
		toSerialize["blueprint_name"] = o.BlueprintName
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableFulfillmentService struct {
	value *FulfillmentService
	isSet bool
}

func (v NullableFulfillmentService) Get() *FulfillmentService {
	return v.value
}

func (v *NullableFulfillmentService) Set(val *FulfillmentService) {
	v.value = val
	v.isSet = true
}

func (v NullableFulfillmentService) IsSet() bool {
	return v.isSet
}

func (v *NullableFulfillmentService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFulfillmentService(val *FulfillmentService) *NullableFulfillmentService {
	return &NullableFulfillmentService{value: val, isSet: true}
}

func (v NullableFulfillmentService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFulfillmentService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
