/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PricingSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricingSpec{}

// PricingSpec struct for PricingSpec
type PricingSpec struct {
	Rate            float32 `json:"rate"`
	Unit            string  `json:"unit"`
	Currency        string  `json:"currency"`
	BillingInterval *int32  `json:"billing_interval,omitempty"`
}

type _PricingSpec PricingSpec

// NewPricingSpec instantiates a new PricingSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricingSpec(rate float32, unit string, currency string) *PricingSpec {
	this := PricingSpec{}
	this.Rate = rate
	this.Unit = unit
	this.Currency = currency
	return &this
}

// NewPricingSpecWithDefaults instantiates a new PricingSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricingSpecWithDefaults() *PricingSpec {
	this := PricingSpec{}
	return &this
}

// GetRate returns the Rate field value
func (o *PricingSpec) GetRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Rate
}

// GetRateOk returns a tuple with the Rate field value
// and a boolean to check if the value has been set.
func (o *PricingSpec) GetRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rate, true
}

// SetRate sets field value
func (o *PricingSpec) SetRate(v float32) {
	o.Rate = v
}

// GetUnit returns the Unit field value
func (o *PricingSpec) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *PricingSpec) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *PricingSpec) SetUnit(v string) {
	o.Unit = v
}

// GetCurrency returns the Currency field value
func (o *PricingSpec) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PricingSpec) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PricingSpec) SetCurrency(v string) {
	o.Currency = v
}

// GetBillingInterval returns the BillingInterval field value if set, zero value otherwise.
func (o *PricingSpec) GetBillingInterval() int32 {
	if o == nil || IsNil(o.BillingInterval) {
		var ret int32
		return ret
	}
	return *o.BillingInterval
}

// GetBillingIntervalOk returns a tuple with the BillingInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricingSpec) GetBillingIntervalOk() (*int32, bool) {
	if o == nil || IsNil(o.BillingInterval) {
		return nil, false
	}
	return o.BillingInterval, true
}

// HasBillingInterval returns a boolean if a field has been set.
func (o *PricingSpec) HasBillingInterval() bool {
	if o != nil && !IsNil(o.BillingInterval) {
		return true
	}

	return false
}

// SetBillingInterval gets a reference to the given int32 and assigns it to the BillingInterval field.
func (o *PricingSpec) SetBillingInterval(v int32) {
	o.BillingInterval = &v
}

func (o PricingSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricingSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rate"] = o.Rate
	toSerialize["unit"] = o.Unit
	toSerialize["currency"] = o.Currency
	if !IsNil(o.BillingInterval) {
		toSerialize["billing_interval"] = o.BillingInterval
	}
	return toSerialize, nil
}

func (o *PricingSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rate",
		"unit",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPricingSpec := _PricingSpec{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPricingSpec)

	if err != nil {
		return err
	}

	*o = PricingSpec(varPricingSpec)

	return err
}

type NullablePricingSpec struct {
	value *PricingSpec
	isSet bool
}

func (v NullablePricingSpec) Get() *PricingSpec {
	return v.value
}

func (v *NullablePricingSpec) Set(val *PricingSpec) {
	v.value = val
	v.isSet = true
}

func (v NullablePricingSpec) IsSet() bool {
	return v.isSet
}

func (v *NullablePricingSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricingSpec(val *PricingSpec) *NullablePricingSpec {
	return &NullablePricingSpec{value: val, isSet: true}
}

func (v NullablePricingSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricingSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
