/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SiteFaultSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteFaultSummary{}

// SiteFaultSummary Per-site fault counts.
type SiteFaultSummary struct {
	SiteId   *string `json:"site_id,omitempty"`
	Open     *int32  `json:"open,omitempty"`
	Critical *int32  `json:"critical,omitempty"`
}

// NewSiteFaultSummary instantiates a new SiteFaultSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteFaultSummary() *SiteFaultSummary {
	this := SiteFaultSummary{}
	return &this
}

// NewSiteFaultSummaryWithDefaults instantiates a new SiteFaultSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteFaultSummaryWithDefaults() *SiteFaultSummary {
	this := SiteFaultSummary{}
	return &this
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *SiteFaultSummary) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteFaultSummary) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *SiteFaultSummary) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *SiteFaultSummary) SetSiteId(v string) {
	o.SiteId = &v
}

// GetOpen returns the Open field value if set, zero value otherwise.
func (o *SiteFaultSummary) GetOpen() int32 {
	if o == nil || IsNil(o.Open) {
		var ret int32
		return ret
	}
	return *o.Open
}

// GetOpenOk returns a tuple with the Open field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteFaultSummary) GetOpenOk() (*int32, bool) {
	if o == nil || IsNil(o.Open) {
		return nil, false
	}
	return o.Open, true
}

// HasOpen returns a boolean if a field has been set.
func (o *SiteFaultSummary) HasOpen() bool {
	if o != nil && !IsNil(o.Open) {
		return true
	}

	return false
}

// SetOpen gets a reference to the given int32 and assigns it to the Open field.
func (o *SiteFaultSummary) SetOpen(v int32) {
	o.Open = &v
}

// GetCritical returns the Critical field value if set, zero value otherwise.
func (o *SiteFaultSummary) GetCritical() int32 {
	if o == nil || IsNil(o.Critical) {
		var ret int32
		return ret
	}
	return *o.Critical
}

// GetCriticalOk returns a tuple with the Critical field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteFaultSummary) GetCriticalOk() (*int32, bool) {
	if o == nil || IsNil(o.Critical) {
		return nil, false
	}
	return o.Critical, true
}

// HasCritical returns a boolean if a field has been set.
func (o *SiteFaultSummary) HasCritical() bool {
	if o != nil && !IsNil(o.Critical) {
		return true
	}

	return false
}

// SetCritical gets a reference to the given int32 and assigns it to the Critical field.
func (o *SiteFaultSummary) SetCritical(v int32) {
	o.Critical = &v
}

func (o SiteFaultSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteFaultSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SiteId) {
		toSerialize["site_id"] = o.SiteId
	}
	if !IsNil(o.Open) {
		toSerialize["open"] = o.Open
	}
	if !IsNil(o.Critical) {
		toSerialize["critical"] = o.Critical
	}
	return toSerialize, nil
}

type NullableSiteFaultSummary struct {
	value *SiteFaultSummary
	isSet bool
}

func (v NullableSiteFaultSummary) Get() *SiteFaultSummary {
	return v.value
}

func (v *NullableSiteFaultSummary) Set(val *SiteFaultSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteFaultSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteFaultSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteFaultSummary(val *SiteFaultSummary) *NullableSiteFaultSummary {
	return &NullableSiteFaultSummary{value: val, isSet: true}
}

func (v NullableSiteFaultSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteFaultSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
