/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DPFHCPRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DPFHCPRequest{}

// DPFHCPRequest Request body for provisioning a DPF hosted control plane.
type DPFHCPRequest struct {
	DpuClusterRef                  DPUClusterReference     `json:"dpuClusterRef"`
	BaseDomain                     string                  `json:"baseDomain"`
	OcpReleaseImage                string                  `json:"ocpReleaseImage"`
	SshKeySecretRef                string                  `json:"sshKeySecretRef"`
	PullSecretRef                  string                  `json:"pullSecretRef"`
	ControlPlaneAvailabilityPolicy *string                 `json:"controlPlaneAvailabilityPolicy,omitempty"`
	VirtualIP                      *string                 `json:"virtualIP,omitempty"`
	EtcdStorageClass               *string                 `json:"etcdStorageClass,omitempty"`
	FlannelEnabled                 *bool                   `json:"flannelEnabled,omitempty"`
	DpuDeploymentRef               *DPUDeploymentReference `json:"dpuDeploymentRef,omitempty"`
	MachineOSURL                   *string                 `json:"machineOSURL,omitempty"`
}

type _DPFHCPRequest DPFHCPRequest

// NewDPFHCPRequest instantiates a new DPFHCPRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDPFHCPRequest(dpuClusterRef DPUClusterReference, baseDomain string, ocpReleaseImage string, sshKeySecretRef string, pullSecretRef string) *DPFHCPRequest {
	this := DPFHCPRequest{}
	this.DpuClusterRef = dpuClusterRef
	this.BaseDomain = baseDomain
	this.OcpReleaseImage = ocpReleaseImage
	this.SshKeySecretRef = sshKeySecretRef
	this.PullSecretRef = pullSecretRef
	return &this
}

// NewDPFHCPRequestWithDefaults instantiates a new DPFHCPRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDPFHCPRequestWithDefaults() *DPFHCPRequest {
	this := DPFHCPRequest{}
	return &this
}

// GetDpuClusterRef returns the DpuClusterRef field value
func (o *DPFHCPRequest) GetDpuClusterRef() DPUClusterReference {
	if o == nil {
		var ret DPUClusterReference
		return ret
	}

	return o.DpuClusterRef
}

// GetDpuClusterRefOk returns a tuple with the DpuClusterRef field value
// and a boolean to check if the value has been set.
func (o *DPFHCPRequest) GetDpuClusterRefOk() (*DPUClusterReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpuClusterRef, true
}

// SetDpuClusterRef sets field value
func (o *DPFHCPRequest) SetDpuClusterRef(v DPUClusterReference) {
	o.DpuClusterRef = v
}

// GetBaseDomain returns the BaseDomain field value
func (o *DPFHCPRequest) GetBaseDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseDomain
}

// GetBaseDomainOk returns a tuple with the BaseDomain field value
// and a boolean to check if the value has been set.
func (o *DPFHCPRequest) GetBaseDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseDomain, true
}

// SetBaseDomain sets field value
func (o *DPFHCPRequest) SetBaseDomain(v string) {
	o.BaseDomain = v
}

// GetOcpReleaseImage returns the OcpReleaseImage field value
func (o *DPFHCPRequest) GetOcpReleaseImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OcpReleaseImage
}

// GetOcpReleaseImageOk returns a tuple with the OcpReleaseImage field value
// and a boolean to check if the value has been set.
func (o *DPFHCPRequest) GetOcpReleaseImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OcpReleaseImage, true
}

// SetOcpReleaseImage sets field value
func (o *DPFHCPRequest) SetOcpReleaseImage(v string) {
	o.OcpReleaseImage = v
}

// GetSshKeySecretRef returns the SshKeySecretRef field value
func (o *DPFHCPRequest) GetSshKeySecretRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SshKeySecretRef
}

// GetSshKeySecretRefOk returns a tuple with the SshKeySecretRef field value
// and a boolean to check if the value has been set.
func (o *DPFHCPRequest) GetSshKeySecretRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SshKeySecretRef, true
}

// SetSshKeySecretRef sets field value
func (o *DPFHCPRequest) SetSshKeySecretRef(v string) {
	o.SshKeySecretRef = v
}

// GetPullSecretRef returns the PullSecretRef field value
func (o *DPFHCPRequest) GetPullSecretRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PullSecretRef
}

// GetPullSecretRefOk returns a tuple with the PullSecretRef field value
// and a boolean to check if the value has been set.
func (o *DPFHCPRequest) GetPullSecretRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PullSecretRef, true
}

// SetPullSecretRef sets field value
func (o *DPFHCPRequest) SetPullSecretRef(v string) {
	o.PullSecretRef = v
}

// GetControlPlaneAvailabilityPolicy returns the ControlPlaneAvailabilityPolicy field value if set, zero value otherwise.
func (o *DPFHCPRequest) GetControlPlaneAvailabilityPolicy() string {
	if o == nil || IsNil(o.ControlPlaneAvailabilityPolicy) {
		var ret string
		return ret
	}
	return *o.ControlPlaneAvailabilityPolicy
}

// GetControlPlaneAvailabilityPolicyOk returns a tuple with the ControlPlaneAvailabilityPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DPFHCPRequest) GetControlPlaneAvailabilityPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.ControlPlaneAvailabilityPolicy) {
		return nil, false
	}
	return o.ControlPlaneAvailabilityPolicy, true
}

// HasControlPlaneAvailabilityPolicy returns a boolean if a field has been set.
func (o *DPFHCPRequest) HasControlPlaneAvailabilityPolicy() bool {
	if o != nil && !IsNil(o.ControlPlaneAvailabilityPolicy) {
		return true
	}

	return false
}

// SetControlPlaneAvailabilityPolicy gets a reference to the given string and assigns it to the ControlPlaneAvailabilityPolicy field.
func (o *DPFHCPRequest) SetControlPlaneAvailabilityPolicy(v string) {
	o.ControlPlaneAvailabilityPolicy = &v
}

// GetVirtualIP returns the VirtualIP field value if set, zero value otherwise.
func (o *DPFHCPRequest) GetVirtualIP() string {
	if o == nil || IsNil(o.VirtualIP) {
		var ret string
		return ret
	}
	return *o.VirtualIP
}

// GetVirtualIPOk returns a tuple with the VirtualIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DPFHCPRequest) GetVirtualIPOk() (*string, bool) {
	if o == nil || IsNil(o.VirtualIP) {
		return nil, false
	}
	return o.VirtualIP, true
}

// HasVirtualIP returns a boolean if a field has been set.
func (o *DPFHCPRequest) HasVirtualIP() bool {
	if o != nil && !IsNil(o.VirtualIP) {
		return true
	}

	return false
}

// SetVirtualIP gets a reference to the given string and assigns it to the VirtualIP field.
func (o *DPFHCPRequest) SetVirtualIP(v string) {
	o.VirtualIP = &v
}

// GetEtcdStorageClass returns the EtcdStorageClass field value if set, zero value otherwise.
func (o *DPFHCPRequest) GetEtcdStorageClass() string {
	if o == nil || IsNil(o.EtcdStorageClass) {
		var ret string
		return ret
	}
	return *o.EtcdStorageClass
}

// GetEtcdStorageClassOk returns a tuple with the EtcdStorageClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DPFHCPRequest) GetEtcdStorageClassOk() (*string, bool) {
	if o == nil || IsNil(o.EtcdStorageClass) {
		return nil, false
	}
	return o.EtcdStorageClass, true
}

// HasEtcdStorageClass returns a boolean if a field has been set.
func (o *DPFHCPRequest) HasEtcdStorageClass() bool {
	if o != nil && !IsNil(o.EtcdStorageClass) {
		return true
	}

	return false
}

// SetEtcdStorageClass gets a reference to the given string and assigns it to the EtcdStorageClass field.
func (o *DPFHCPRequest) SetEtcdStorageClass(v string) {
	o.EtcdStorageClass = &v
}

// GetFlannelEnabled returns the FlannelEnabled field value if set, zero value otherwise.
func (o *DPFHCPRequest) GetFlannelEnabled() bool {
	if o == nil || IsNil(o.FlannelEnabled) {
		var ret bool
		return ret
	}
	return *o.FlannelEnabled
}

// GetFlannelEnabledOk returns a tuple with the FlannelEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DPFHCPRequest) GetFlannelEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.FlannelEnabled) {
		return nil, false
	}
	return o.FlannelEnabled, true
}

// HasFlannelEnabled returns a boolean if a field has been set.
func (o *DPFHCPRequest) HasFlannelEnabled() bool {
	if o != nil && !IsNil(o.FlannelEnabled) {
		return true
	}

	return false
}

// SetFlannelEnabled gets a reference to the given bool and assigns it to the FlannelEnabled field.
func (o *DPFHCPRequest) SetFlannelEnabled(v bool) {
	o.FlannelEnabled = &v
}

// GetDpuDeploymentRef returns the DpuDeploymentRef field value if set, zero value otherwise.
func (o *DPFHCPRequest) GetDpuDeploymentRef() DPUDeploymentReference {
	if o == nil || IsNil(o.DpuDeploymentRef) {
		var ret DPUDeploymentReference
		return ret
	}
	return *o.DpuDeploymentRef
}

// GetDpuDeploymentRefOk returns a tuple with the DpuDeploymentRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DPFHCPRequest) GetDpuDeploymentRefOk() (*DPUDeploymentReference, bool) {
	if o == nil || IsNil(o.DpuDeploymentRef) {
		return nil, false
	}
	return o.DpuDeploymentRef, true
}

// HasDpuDeploymentRef returns a boolean if a field has been set.
func (o *DPFHCPRequest) HasDpuDeploymentRef() bool {
	if o != nil && !IsNil(o.DpuDeploymentRef) {
		return true
	}

	return false
}

// SetDpuDeploymentRef gets a reference to the given DPUDeploymentReference and assigns it to the DpuDeploymentRef field.
func (o *DPFHCPRequest) SetDpuDeploymentRef(v DPUDeploymentReference) {
	o.DpuDeploymentRef = &v
}

// GetMachineOSURL returns the MachineOSURL field value if set, zero value otherwise.
func (o *DPFHCPRequest) GetMachineOSURL() string {
	if o == nil || IsNil(o.MachineOSURL) {
		var ret string
		return ret
	}
	return *o.MachineOSURL
}

// GetMachineOSURLOk returns a tuple with the MachineOSURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DPFHCPRequest) GetMachineOSURLOk() (*string, bool) {
	if o == nil || IsNil(o.MachineOSURL) {
		return nil, false
	}
	return o.MachineOSURL, true
}

// HasMachineOSURL returns a boolean if a field has been set.
func (o *DPFHCPRequest) HasMachineOSURL() bool {
	if o != nil && !IsNil(o.MachineOSURL) {
		return true
	}

	return false
}

// SetMachineOSURL gets a reference to the given string and assigns it to the MachineOSURL field.
func (o *DPFHCPRequest) SetMachineOSURL(v string) {
	o.MachineOSURL = &v
}

func (o DPFHCPRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DPFHCPRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dpuClusterRef"] = o.DpuClusterRef
	toSerialize["baseDomain"] = o.BaseDomain
	toSerialize["ocpReleaseImage"] = o.OcpReleaseImage
	toSerialize["sshKeySecretRef"] = o.SshKeySecretRef
	toSerialize["pullSecretRef"] = o.PullSecretRef
	if !IsNil(o.ControlPlaneAvailabilityPolicy) {
		toSerialize["controlPlaneAvailabilityPolicy"] = o.ControlPlaneAvailabilityPolicy
	}
	if !IsNil(o.VirtualIP) {
		toSerialize["virtualIP"] = o.VirtualIP
	}
	if !IsNil(o.EtcdStorageClass) {
		toSerialize["etcdStorageClass"] = o.EtcdStorageClass
	}
	if !IsNil(o.FlannelEnabled) {
		toSerialize["flannelEnabled"] = o.FlannelEnabled
	}
	if !IsNil(o.DpuDeploymentRef) {
		toSerialize["dpuDeploymentRef"] = o.DpuDeploymentRef
	}
	if !IsNil(o.MachineOSURL) {
		toSerialize["machineOSURL"] = o.MachineOSURL
	}
	return toSerialize, nil
}

func (o *DPFHCPRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dpuClusterRef",
		"baseDomain",
		"ocpReleaseImage",
		"sshKeySecretRef",
		"pullSecretRef",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDPFHCPRequest := _DPFHCPRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDPFHCPRequest)

	if err != nil {
		return err
	}

	*o = DPFHCPRequest(varDPFHCPRequest)

	return err
}

type NullableDPFHCPRequest struct {
	value *DPFHCPRequest
	isSet bool
}

func (v NullableDPFHCPRequest) Get() *DPFHCPRequest {
	return v.value
}

func (v *NullableDPFHCPRequest) Set(val *DPFHCPRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDPFHCPRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDPFHCPRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDPFHCPRequest(val *DPFHCPRequest) *NullableDPFHCPRequest {
	return &NullableDPFHCPRequest{value: val, isSet: true}
}

func (v NullableDPFHCPRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDPFHCPRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
