/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the FaultEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FaultEvent{}

// FaultEvent An infrastructure fault tracked through its full lifecycle.
type FaultEvent struct {
	Id                    *string                `json:"id,omitempty"`
	OrgId                 *string                `json:"org_id,omitempty"`
	TenantId              *string                `json:"tenant_id,omitempty"`
	SiteId                *string                `json:"site_id,omitempty"`
	MachineId             *string                `json:"machine_id,omitempty"`
	InstanceId            *string                `json:"instance_id,omitempty"`
	Source                *string                `json:"source,omitempty"`
	Severity              *string                `json:"severity,omitempty"`
	Component             *string                `json:"component,omitempty"`
	Classification        *string                `json:"classification,omitempty"`
	Message               *string                `json:"message,omitempty"`
	State                 *string                `json:"state,omitempty"`
	DetectedAt            *time.Time             `json:"detected_at,omitempty"`
	AcknowledgedAt        *time.Time             `json:"acknowledged_at,omitempty"`
	ResolvedAt            *time.Time             `json:"resolved_at,omitempty"`
	SuppressedUntil       *time.Time             `json:"suppressed_until,omitempty"`
	RemediationWorkflowId *string                `json:"remediation_workflow_id,omitempty"`
	RemediationAttempts   *int32                 `json:"remediation_attempts,omitempty"`
	EscalationLevel       *int32                 `json:"escalation_level,omitempty"`
	Metadata              map[string]interface{} `json:"metadata,omitempty"`
	CreatedAt             *time.Time             `json:"created_at,omitempty"`
	UpdatedAt             *time.Time             `json:"updated_at,omitempty"`
}

// NewFaultEvent instantiates a new FaultEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFaultEvent() *FaultEvent {
	this := FaultEvent{}
	return &this
}

// NewFaultEventWithDefaults instantiates a new FaultEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFaultEventWithDefaults() *FaultEvent {
	this := FaultEvent{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FaultEvent) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FaultEvent) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FaultEvent) SetId(v string) {
	o.Id = &v
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *FaultEvent) GetOrgId() string {
	if o == nil || IsNil(o.OrgId) {
		var ret string
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetOrgIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *FaultEvent) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given string and assigns it to the OrgId field.
func (o *FaultEvent) SetOrgId(v string) {
	o.OrgId = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *FaultEvent) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *FaultEvent) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *FaultEvent) SetTenantId(v string) {
	o.TenantId = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *FaultEvent) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *FaultEvent) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *FaultEvent) SetSiteId(v string) {
	o.SiteId = &v
}

// GetMachineId returns the MachineId field value if set, zero value otherwise.
func (o *FaultEvent) GetMachineId() string {
	if o == nil || IsNil(o.MachineId) {
		var ret string
		return ret
	}
	return *o.MachineId
}

// GetMachineIdOk returns a tuple with the MachineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetMachineIdOk() (*string, bool) {
	if o == nil || IsNil(o.MachineId) {
		return nil, false
	}
	return o.MachineId, true
}

// HasMachineId returns a boolean if a field has been set.
func (o *FaultEvent) HasMachineId() bool {
	if o != nil && !IsNil(o.MachineId) {
		return true
	}

	return false
}

// SetMachineId gets a reference to the given string and assigns it to the MachineId field.
func (o *FaultEvent) SetMachineId(v string) {
	o.MachineId = &v
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *FaultEvent) GetInstanceId() string {
	if o == nil || IsNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceId) {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *FaultEvent) HasInstanceId() bool {
	if o != nil && !IsNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *FaultEvent) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *FaultEvent) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *FaultEvent) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *FaultEvent) SetSource(v string) {
	o.Source = &v
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *FaultEvent) GetSeverity() string {
	if o == nil || IsNil(o.Severity) {
		var ret string
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetSeverityOk() (*string, bool) {
	if o == nil || IsNil(o.Severity) {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *FaultEvent) HasSeverity() bool {
	if o != nil && !IsNil(o.Severity) {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given string and assigns it to the Severity field.
func (o *FaultEvent) SetSeverity(v string) {
	o.Severity = &v
}

// GetComponent returns the Component field value if set, zero value otherwise.
func (o *FaultEvent) GetComponent() string {
	if o == nil || IsNil(o.Component) {
		var ret string
		return ret
	}
	return *o.Component
}

// GetComponentOk returns a tuple with the Component field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetComponentOk() (*string, bool) {
	if o == nil || IsNil(o.Component) {
		return nil, false
	}
	return o.Component, true
}

// HasComponent returns a boolean if a field has been set.
func (o *FaultEvent) HasComponent() bool {
	if o != nil && !IsNil(o.Component) {
		return true
	}

	return false
}

// SetComponent gets a reference to the given string and assigns it to the Component field.
func (o *FaultEvent) SetComponent(v string) {
	o.Component = &v
}

// GetClassification returns the Classification field value if set, zero value otherwise.
func (o *FaultEvent) GetClassification() string {
	if o == nil || IsNil(o.Classification) {
		var ret string
		return ret
	}
	return *o.Classification
}

// GetClassificationOk returns a tuple with the Classification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetClassificationOk() (*string, bool) {
	if o == nil || IsNil(o.Classification) {
		return nil, false
	}
	return o.Classification, true
}

// HasClassification returns a boolean if a field has been set.
func (o *FaultEvent) HasClassification() bool {
	if o != nil && !IsNil(o.Classification) {
		return true
	}

	return false
}

// SetClassification gets a reference to the given string and assigns it to the Classification field.
func (o *FaultEvent) SetClassification(v string) {
	o.Classification = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FaultEvent) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FaultEvent) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FaultEvent) SetMessage(v string) {
	o.Message = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *FaultEvent) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *FaultEvent) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *FaultEvent) SetState(v string) {
	o.State = &v
}

// GetDetectedAt returns the DetectedAt field value if set, zero value otherwise.
func (o *FaultEvent) GetDetectedAt() time.Time {
	if o == nil || IsNil(o.DetectedAt) {
		var ret time.Time
		return ret
	}
	return *o.DetectedAt
}

// GetDetectedAtOk returns a tuple with the DetectedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetDetectedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DetectedAt) {
		return nil, false
	}
	return o.DetectedAt, true
}

// HasDetectedAt returns a boolean if a field has been set.
func (o *FaultEvent) HasDetectedAt() bool {
	if o != nil && !IsNil(o.DetectedAt) {
		return true
	}

	return false
}

// SetDetectedAt gets a reference to the given time.Time and assigns it to the DetectedAt field.
func (o *FaultEvent) SetDetectedAt(v time.Time) {
	o.DetectedAt = &v
}

// GetAcknowledgedAt returns the AcknowledgedAt field value if set, zero value otherwise.
func (o *FaultEvent) GetAcknowledgedAt() time.Time {
	if o == nil || IsNil(o.AcknowledgedAt) {
		var ret time.Time
		return ret
	}
	return *o.AcknowledgedAt
}

// GetAcknowledgedAtOk returns a tuple with the AcknowledgedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetAcknowledgedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AcknowledgedAt) {
		return nil, false
	}
	return o.AcknowledgedAt, true
}

// HasAcknowledgedAt returns a boolean if a field has been set.
func (o *FaultEvent) HasAcknowledgedAt() bool {
	if o != nil && !IsNil(o.AcknowledgedAt) {
		return true
	}

	return false
}

// SetAcknowledgedAt gets a reference to the given time.Time and assigns it to the AcknowledgedAt field.
func (o *FaultEvent) SetAcknowledgedAt(v time.Time) {
	o.AcknowledgedAt = &v
}

// GetResolvedAt returns the ResolvedAt field value if set, zero value otherwise.
func (o *FaultEvent) GetResolvedAt() time.Time {
	if o == nil || IsNil(o.ResolvedAt) {
		var ret time.Time
		return ret
	}
	return *o.ResolvedAt
}

// GetResolvedAtOk returns a tuple with the ResolvedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetResolvedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ResolvedAt) {
		return nil, false
	}
	return o.ResolvedAt, true
}

// HasResolvedAt returns a boolean if a field has been set.
func (o *FaultEvent) HasResolvedAt() bool {
	if o != nil && !IsNil(o.ResolvedAt) {
		return true
	}

	return false
}

// SetResolvedAt gets a reference to the given time.Time and assigns it to the ResolvedAt field.
func (o *FaultEvent) SetResolvedAt(v time.Time) {
	o.ResolvedAt = &v
}

// GetSuppressedUntil returns the SuppressedUntil field value if set, zero value otherwise.
func (o *FaultEvent) GetSuppressedUntil() time.Time {
	if o == nil || IsNil(o.SuppressedUntil) {
		var ret time.Time
		return ret
	}
	return *o.SuppressedUntil
}

// GetSuppressedUntilOk returns a tuple with the SuppressedUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetSuppressedUntilOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SuppressedUntil) {
		return nil, false
	}
	return o.SuppressedUntil, true
}

// HasSuppressedUntil returns a boolean if a field has been set.
func (o *FaultEvent) HasSuppressedUntil() bool {
	if o != nil && !IsNil(o.SuppressedUntil) {
		return true
	}

	return false
}

// SetSuppressedUntil gets a reference to the given time.Time and assigns it to the SuppressedUntil field.
func (o *FaultEvent) SetSuppressedUntil(v time.Time) {
	o.SuppressedUntil = &v
}

// GetRemediationWorkflowId returns the RemediationWorkflowId field value if set, zero value otherwise.
func (o *FaultEvent) GetRemediationWorkflowId() string {
	if o == nil || IsNil(o.RemediationWorkflowId) {
		var ret string
		return ret
	}
	return *o.RemediationWorkflowId
}

// GetRemediationWorkflowIdOk returns a tuple with the RemediationWorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetRemediationWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.RemediationWorkflowId) {
		return nil, false
	}
	return o.RemediationWorkflowId, true
}

// HasRemediationWorkflowId returns a boolean if a field has been set.
func (o *FaultEvent) HasRemediationWorkflowId() bool {
	if o != nil && !IsNil(o.RemediationWorkflowId) {
		return true
	}

	return false
}

// SetRemediationWorkflowId gets a reference to the given string and assigns it to the RemediationWorkflowId field.
func (o *FaultEvent) SetRemediationWorkflowId(v string) {
	o.RemediationWorkflowId = &v
}

// GetRemediationAttempts returns the RemediationAttempts field value if set, zero value otherwise.
func (o *FaultEvent) GetRemediationAttempts() int32 {
	if o == nil || IsNil(o.RemediationAttempts) {
		var ret int32
		return ret
	}
	return *o.RemediationAttempts
}

// GetRemediationAttemptsOk returns a tuple with the RemediationAttempts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetRemediationAttemptsOk() (*int32, bool) {
	if o == nil || IsNil(o.RemediationAttempts) {
		return nil, false
	}
	return o.RemediationAttempts, true
}

// HasRemediationAttempts returns a boolean if a field has been set.
func (o *FaultEvent) HasRemediationAttempts() bool {
	if o != nil && !IsNil(o.RemediationAttempts) {
		return true
	}

	return false
}

// SetRemediationAttempts gets a reference to the given int32 and assigns it to the RemediationAttempts field.
func (o *FaultEvent) SetRemediationAttempts(v int32) {
	o.RemediationAttempts = &v
}

// GetEscalationLevel returns the EscalationLevel field value if set, zero value otherwise.
func (o *FaultEvent) GetEscalationLevel() int32 {
	if o == nil || IsNil(o.EscalationLevel) {
		var ret int32
		return ret
	}
	return *o.EscalationLevel
}

// GetEscalationLevelOk returns a tuple with the EscalationLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetEscalationLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.EscalationLevel) {
		return nil, false
	}
	return o.EscalationLevel, true
}

// HasEscalationLevel returns a boolean if a field has been set.
func (o *FaultEvent) HasEscalationLevel() bool {
	if o != nil && !IsNil(o.EscalationLevel) {
		return true
	}

	return false
}

// SetEscalationLevel gets a reference to the given int32 and assigns it to the EscalationLevel field.
func (o *FaultEvent) SetEscalationLevel(v int32) {
	o.EscalationLevel = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *FaultEvent) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *FaultEvent) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *FaultEvent) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FaultEvent) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FaultEvent) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FaultEvent) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *FaultEvent) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaultEvent) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *FaultEvent) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *FaultEvent) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o FaultEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FaultEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrgId) {
		toSerialize["org_id"] = o.OrgId
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.SiteId) {
		toSerialize["site_id"] = o.SiteId
	}
	if !IsNil(o.MachineId) {
		toSerialize["machine_id"] = o.MachineId
	}
	if !IsNil(o.InstanceId) {
		toSerialize["instance_id"] = o.InstanceId
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Severity) {
		toSerialize["severity"] = o.Severity
	}
	if !IsNil(o.Component) {
		toSerialize["component"] = o.Component
	}
	if !IsNil(o.Classification) {
		toSerialize["classification"] = o.Classification
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.DetectedAt) {
		toSerialize["detected_at"] = o.DetectedAt
	}
	if !IsNil(o.AcknowledgedAt) {
		toSerialize["acknowledged_at"] = o.AcknowledgedAt
	}
	if !IsNil(o.ResolvedAt) {
		toSerialize["resolved_at"] = o.ResolvedAt
	}
	if !IsNil(o.SuppressedUntil) {
		toSerialize["suppressed_until"] = o.SuppressedUntil
	}
	if !IsNil(o.RemediationWorkflowId) {
		toSerialize["remediation_workflow_id"] = o.RemediationWorkflowId
	}
	if !IsNil(o.RemediationAttempts) {
		toSerialize["remediation_attempts"] = o.RemediationAttempts
	}
	if !IsNil(o.EscalationLevel) {
		toSerialize["escalation_level"] = o.EscalationLevel
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableFaultEvent struct {
	value *FaultEvent
	isSet bool
}

func (v NullableFaultEvent) Get() *FaultEvent {
	return v.value
}

func (v *NullableFaultEvent) Set(val *FaultEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableFaultEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableFaultEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFaultEvent(val *FaultEvent) *NullableFaultEvent {
	return &NullableFaultEvent{value: val, isSet: true}
}

func (v NullableFaultEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFaultEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
